-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd("highlight clear")
end
vim.g.colors_name = "base16-da-one-ocean"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "TSAttribute" })
hi(0, "@boolean", { link = "TSBoolean" })
hi(0, "@character", { link = "TSCharacter" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@class", { link = "TSType" })
hi(0, "@comment", { link = "TSComment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.hint", { link = "DiagnosticHint" })
hi(0, "@comment.info", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "TSConditional" })
hi(0, "@constant", { link = "TSConstant" })
hi(0, "@constant.builtin", { link = "TSConstant" })
hi(0, "@constant.macro", { link = "TSConstant" })
hi(0, "@constructor", { link = "TSConstructor" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@decorator", { link = "Identifier" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "@text.diff.delete" })
hi(0, "@diff.plus", { link = "@text.diff.add" })
hi(0, "@enum", { link = "TSType" })
hi(0, "@enumMember", { link = "Constant" })
hi(0, "@error", { link = "TSError" })
hi(0, "@event", { link = "Identifier" })
hi(0, "@exception", { link = "TSException" })
hi(0, "@field", { link = "TSField" })
hi(0, "@float", { link = "TSFloat" })
hi(0, "@function", { link = "TSFunction" })
hi(0, "@function.builtin", { link = "TSFuncBuiltin" })
hi(0, "@function.call", { link = "TSFunction" })
hi(0, "@function.macro", { link = "TSFuncMacro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "TSInclude" })
hi(0, "@interface", { link = "Structure" })
hi(0, "@keyword", { link = "TSKeyword" })
hi(0, "@keyword.conditional", { link = "@conditional" })
hi(0, "@keyword.debug", { link = "@debug" })
hi(0, "@keyword.directive", { link = "@preproc" })
hi(0, "@keyword.directive.define", { link = "@define" })
hi(0, "@keyword.exception", { link = "@exception" })
hi(0, "@keyword.function", { link = "TSKeywordFunction" })
hi(0, "@keyword.import", { link = "@include" })
hi(0, "@keyword.operator", { link = "TSKeywordOperator" })
hi(0, "@keyword.repeat", { link = "@repeat" })
hi(0, "@keyword.return", { link = "TSKeyword" })
hi(0, "@keyword.storage", { link = "@storageclass" })
hi(0, "@label", { link = "TSLabel" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@function.macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.italic", { link = "Italic" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@string.special" })
hi(0, "@markup.link.url", { link = "@text.uri" })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.strikethrough", { link = "@text.strikethrough" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@method", { link = "TSMethod" })
hi(0, "@method.call", { link = "TSMethod" })
hi(0, "@modifier", { link = "Identifier" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@namespace", { link = "TSNamespace" })
hi(0, "@none", { link = "TSNone" })
hi(0, "@number", { link = "TSNumber" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@operator", { link = "TSOperator" })
hi(0, "@parameter", { link = "TSParameter" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { link = "TSProperty" })
hi(0, "@punctuation.bracket", { link = "TSPunctBracket" })
hi(0, "@punctuation.delimiter", { link = "TSPunctDelimiter" })
hi(0, "@punctuation.special", { link = "TSPunctSpecial" })
hi(0, "@regexp", { link = "TSStringRegex" })
hi(0, "@repeat", { link = "TSRepeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string", { link = "TSString" })
hi(0, "@string.escape", { link = "TSStringEscape" })
hi(0, "@string.regex", { link = "TSStringRegex" })
hi(0, "@string.regexp", { link = "@string.regex" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.symbol", { link = "@symbol" })
hi(0, "@string.special.url", { link = "@text.uri" })
hi(0, "@struct", { link = "TSType" })
hi(0, "@symbol", { link = "TSSymbol" })
hi(0, "@tag", { link = "TSTag" })
hi(0, "@tag.attribute", { link = "TSAttribute" })
hi(0, "@tag.delimiter", { link = "TSTagDelimiter" })
hi(0, "@text", { link = "TSText" })
hi(0, "@text.danger", { link = "DiagnosticError" })
hi(0, "@text.diff.add", { link = "DiffAdd" })
hi(0, "@text.diff.delete", { link = "DiffDelete" })
hi(0, "@text.emphasis", { link = "TSEmphasis" })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.literal", { link = "TSLiteral" })
hi(0, "@text.math", { link = "Number" })
hi(0, "@text.note", { link = "Tag" })
hi(0, "@text.reference", { link = "TSParameterReference" })
hi(0, "@text.strike", { link = "TSStrike" })
hi(0, "@text.strong", { link = "TSStrong" })
hi(0, "@text.title", { link = "TSTitle" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "TSUnderline" })
hi(0, "@text.uri", { link = "TSURI" })
hi(0, "@text.warning", { link = "DiagnosticWarn" })
hi(0, "@type", { link = "TSType" })
hi(0, "@type.builtin", { link = "TSTypeBuiltin" })
hi(0, "@type.definition", { link = "TSType" })
hi(0, "@type.qualifier", { link = "TSKeyword" })
hi(0, "@typeParameter", { link = "Type" })
hi(0, "@variable", { link = "TSVariable" })
hi(0, "@variable.builtin", { link = "TSVariableBuiltin" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ffc387" })
hi(0, "Character", { fg = "#fa7883" })
hi(0, "CmpDocumentation", { bg = "#171726", fg = "#ffffff" })
hi(0, "CmpDocumentationBorder", { bg = "#171726", fg = "#ffffff" })
hi(0, "CmpItemAbbr", { bg = "#22273d", fg = "#ffffff" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#878d96", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#6bb8ff" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#6bb8ff" })
hi(0, "CmpItemKindClass", { fg = "#ff9470" })
hi(0, "CmpItemKindConstant", { fg = "#ffc387" })
hi(0, "CmpItemKindConstructor", { fg = "#6bb8ff" })
hi(0, "CmpItemKindDefault", { fg = "#ffffff" })
hi(0, "CmpItemKindEnum", { fg = "#ff9470" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff9470" })
hi(0, "CmpItemKindEvent", { fg = "#ff9470" })
hi(0, "CmpItemKindField", { fg = "#fa7883" })
hi(0, "CmpItemKindFunction", { fg = "#6bb8ff" })
hi(0, "CmpItemKindInterface", { fg = "#ff9470" })
hi(0, "CmpItemKindKeyword", { fg = "#e799ff" })
hi(0, "CmpItemKindMethod", { fg = "#6bb8ff" })
hi(0, "CmpItemKindModule", { fg = "#ffffff" })
hi(0, "CmpItemKindOperator", { fg = "#ffffff" })
hi(0, "CmpItemKindProperty", { fg = "#fa7883" })
hi(0, "CmpItemKindReference", { fg = "#fa7883" })
hi(0, "CmpItemKindSnippet", { fg = "#c8c8c8" })
hi(0, "CmpItemKindStruct", { fg = "#ff9470" })
hi(0, "CmpItemKindTypeParameter", { fg = "#ff9470" })
hi(0, "CmpItemKindUnit", { fg = "#ff9470" })
hi(0, "CmpItemKindValue", { fg = "#ffc387" })
hi(0, "CmpItemKindVariable", { fg = "#fa7883" })
hi(0, "CmpItemMenu", { fg = "#c8c8c8" })
hi(0, "ColorColumn", { bg = "#22273d" })
hi(0, "Comment", { fg = "#878d96" })
hi(0, "Conceal", { bg = "#171726", fg = "#6bb8ff" })
hi(0, "Conditional", { fg = "#e799ff" })
hi(0, "Constant", { fg = "#ffc387" })
hi(0, "Cursor", { bg = "#ffffff", fg = "#171726" })
hi(0, "CursorColumn", { bg = "#22273d" })
hi(0, "CursorLine", { bg = "#22273d" })
hi(0, "CursorLineNr", { bg = "#22273d", fg = "#c8c8c8" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#98c379" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#525866" })
hi(0, "DapUIBreakpointsInfo", { fg = "#98c379" })
hi(0, "DapUIBreakpointsLine", { link = "DapUILineNumber" })
hi(0, "DapUIBreakpointsPath", { fg = "#6bb8ff" })
hi(0, "DapUICurrentFrameName", { link = "DapUIBreakpointsCurrentLine" })
hi(0, "DapUIDecoration", { fg = "#6bb8ff" })
hi(0, "DapUIEndofBuffer", { link = "EndOfBuffer" })
hi(0, "DapUIFloatBorder", { fg = "#6bb8ff" })
hi(0, "DapUIFloatNormal", { link = "NormalFloat" })
hi(0, "DapUIFrameName", { link = "Normal" })
hi(0, "DapUILineNumber", { fg = "#6bb8ff" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#6bb8ff" })
hi(0, "DapUINormal", { link = "Normal" })
hi(0, "DapUINormalNC", { link = "Normal" })
hi(0, "DapUIPlayPause", { fg = "#98c379" })
hi(0, "DapUIPlayPauseNC", { fg = "#98c379" })
hi(0, "DapUIRestart", { fg = "#98c379" })
hi(0, "DapUIRestartNC", { fg = "#98c379" })
hi(0, "DapUIScope", { fg = "#6bb8ff" })
hi(0, "DapUISource", { fg = "#e799ff" })
hi(0, "DapUIStepBack", { fg = "#6bb8ff" })
hi(0, "DapUIStepBackNC", { fg = "#6bb8ff" })
hi(0, "DapUIStepInto", { fg = "#6bb8ff" })
hi(0, "DapUIStepIntoNC", { fg = "#6bb8ff" })
hi(0, "DapUIStepOut", { fg = "#6bb8ff" })
hi(0, "DapUIStepOutNC", { fg = "#6bb8ff" })
hi(0, "DapUIStepOver", { fg = "#6bb8ff" })
hi(0, "DapUIStepOverNC", { fg = "#6bb8ff" })
hi(0, "DapUIStop", { fg = "#fa7883" })
hi(0, "DapUIStopNC", { fg = "#fa7883" })
hi(0, "DapUIStoppedThread", { fg = "#6bb8ff" })
hi(0, "DapUIThread", { fg = "#98c379" })
hi(0, "DapUIType", { fg = "#e799ff" })
hi(0, "DapUIUnavailable", { fg = "#525866" })
hi(0, "DapUIUnavailableNC", { fg = "#525866" })
hi(0, "DapUIValue", { link = "Normal" })
hi(0, "DapUIVariable", { link = "Normal" })
hi(0, "DapUIWatchesEmpty", { fg = "#fa7883" })
hi(0, "DapUIWatchesError", { fg = "#fa7883" })
hi(0, "DapUIWatchesValue", { fg = "#98c379" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#6bb8ff" })
hi(0, "Debug", { fg = "#fa7883" })
hi(0, "Define", { fg = "#e799ff" })
hi(0, "Delimiter", { fg = "#b3684f" })
hi(0, "DiagnosticError", { fg = "#fa7883" })
hi(0, "DiagnosticHint", { fg = "#8af5ff" })
hi(0, "DiagnosticInfo", { fg = "#6bb8ff" })
hi(0, "DiagnosticUnderlineError", { sp = "#fa7883", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8af5ff", undercurl = true })
hi(0, "DiagnosticUnderlineInformation", { sp = "#b3684f", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e799ff", undercurl = true })
hi(0, "DiagnosticUnderlineWarning", { sp = "#e799ff", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#e799ff" })
hi(0, "DiffAdd", { bg = "#171726", fg = "#98c379" })
hi(0, "DiffAdded", { bg = "#171726", fg = "#98c379" })
hi(0, "DiffChange", { bg = "#171726", fg = "#878d96" })
hi(0, "DiffDelete", { bg = "#171726", fg = "#fa7883" })
hi(0, "DiffFile", { bg = "#171726", fg = "#fa7883" })
hi(0, "DiffLine", { bg = "#171726", fg = "#6bb8ff" })
hi(0, "DiffNewFile", { bg = "#171726", fg = "#98c379" })
hi(0, "DiffRemoved", { bg = "#171726", fg = "#fa7883" })
hi(0, "DiffText", { bg = "#171726", fg = "#6bb8ff" })
hi(0, "Directory", { fg = "#6bb8ff" })
hi(0, "Error", { bg = "#171726", fg = "#fa7883" })
hi(0, "ErrorMsg", { bg = "#171726", fg = "#fa7883" })
hi(0, "Exception", { fg = "#fa7883" })
hi(0, "Float", { fg = "#ffc387" })
hi(0, "FloatBorder", { bg = "#171726", fg = "#ffffff" })
hi(0, "FoldColumn", { bg = "#171726", fg = "#8af5ff" })
hi(0, "Folded", { bg = "#22273d", fg = "#878d96" })
hi(0, "Function", { fg = "#6bb8ff" })
hi(0, "GitGutterAdd", { bg = "#171726", fg = "#98c379" })
hi(0, "GitGutterChange", { bg = "#171726", fg = "#6bb8ff" })
hi(0, "GitGutterChangeDelete", { bg = "#171726", fg = "#e799ff" })
hi(0, "GitGutterDelete", { bg = "#171726", fg = "#fa7883" })
hi(0, "GitSignsStagedAdd", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedAddCul", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedAddLn", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedAddNr", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedChange", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedChangeCul", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedChangeLn", { bg = "#171726", fg = "#43464b" })
hi(0, "GitSignsStagedChangeNr", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedChangedelete", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedChangedeleteCul", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#171726", fg = "#43464b" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#171726", fg = "#355c7f" })
hi(0, "GitSignsStagedDelete", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedDeleteCul", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedTopdelete", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedTopdeleteCul", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#171726", fg = "#7d3c41" })
hi(0, "GitSignsStagedUntracked", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedUntrackedCul", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#171726", fg = "#4c613c" })
hi(0, "GitSignsStagedUntrackedNr", { bg = "#171726", fg = "#4c613c" })
hi(0, "IblIndent", { fg = "#525866", nocombine = true })
hi(0, "IblScope", { fg = "#c8c8c8", nocombine = true })
hi(0, "IblWhitespace", { link = "Whitespace" })
hi(0, "Identifier", { fg = "#fa7883" })
hi(0, "IlluminatedWordRead", { sp = "#c8c8c8", underline = true })
hi(0, "IlluminatedWordText", { sp = "#c8c8c8", underline = true })
hi(0, "IlluminatedWordWrite", { sp = "#c8c8c8", underline = true })
hi(0, "IncSearch", { bg = "#ffc387", fg = "#22273d" })
hi(0, "Include", { fg = "#6bb8ff" })
hi(0, "IndentBlanklineChar", { fg = "#525866", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#c8c8c8", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#e799ff" })
hi(0, "Label", { fg = "#ff9470" })
hi(0, "LineNr", { fg = "#cdd6f4" })
hi(0, "LineNrAbove", { fg = "#585b70" })
hi(0, "LineNrBelow", { fg = "#585b70" })
hi(0, "LspDiagnosticsDefaultError", { link = "DiagnosticError" })
hi(0, "LspDiagnosticsDefaultHint", { link = "DiagnosticHint" })
hi(0, "LspDiagnosticsDefaultInformation", { link = "DiagnosticInfo" })
hi(0, "LspDiagnosticsDefaultWarning", { link = "DiagnosticWarn" })
hi(0, "LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
hi(0, "LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })
hi(
  0,
  "LspDiagnosticsUnderlineInformation",
  { link = "DiagnosticUnderlineInformation" }
)
hi(0, "LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarning" })
hi(0, "LspInlayHint", { fg = "#878d96", italic = true })
hi(0, "LspReferenceRead", { sp = "#c8c8c8", underline = true })
hi(0, "LspReferenceText", { sp = "#c8c8c8", underline = true })
hi(0, "LspReferenceWrite", { sp = "#c8c8c8", underline = true })
hi(0, "Macro", { fg = "#fa7883" })
hi(0, "MatchParen", { bg = "#878d96" })
hi(0, "MiniCompletionActiveParameter", { link = "CursorLine" })
hi(0, "MiniHipatternsFixme", { bold = true, fg = "#fa7883", reverse = true })
hi(0, "MiniHipatternsHack", { bold = true, fg = "#e799ff", reverse = true })
hi(0, "MiniHipatternsNote", { bold = true, fg = "#8af5ff", reverse = true })
hi(0, "MiniHipatternsTodo", { bold = true, fg = "#6bb8ff", reverse = true })
hi(0, "MiniHipatterns_000000_bg", { bg = "#000000", fg = "#ffffff" })
hi(0, "MiniHipatterns_000001_bg", { bg = "#000001", fg = "#ffffff" })
hi(0, "MiniHipatterns_000002_bg", { bg = "#000002", fg = "#ffffff" })
hi(0, "MiniHipatterns_000003_bg", { bg = "#000003", fg = "#ffffff" })
hi(0, "MiniHipatterns_00008b_bg", { bg = "#00008b", fg = "#ffffff" })
hi(0, "MiniHipatterns_006400_bg", { bg = "#006400", fg = "#ffffff" })
hi(0, "MiniHipatterns_008b8b_bg", { bg = "#008b8b", fg = "#000000" })
hi(0, "MiniHipatterns_04d1f9_bg", { bg = "#04d1f9", fg = "#000000" })
hi(0, "MiniHipatterns_181825_bg", { bg = "#181825", fg = "#ffffff" })
hi(0, "MiniHipatterns_191724_bg", { bg = "#191724", fg = "#ffffff" })
hi(0, "MiniHipatterns_1d1b2a_bg", { bg = "#1d1b2a", fg = "#ffffff" })
hi(0, "MiniHipatterns_1d2534_bg", { bg = "#1d2534", fg = "#ffffff" })
hi(0, "MiniHipatterns_1e1e2e_bg", { bg = "#1e1e2e", fg = "#ffffff" })
hi(0, "MiniHipatterns_1e2a39_bg", { bg = "#1e2a39", fg = "#ffffff" })
hi(0, "MiniHipatterns_1f1d2e_bg", { bg = "#1f1d2e", fg = "#ffffff" })
hi(0, "MiniHipatterns_1f2e3f_bg", { bg = "#1f2e3f", fg = "#ffffff" })
hi(0, "MiniHipatterns_221f2e_bg", { bg = "#221f2e", fg = "#ffffff" })
hi(0, "MiniHipatterns_26233a_bg", { bg = "#26233a", fg = "#ffffff" })
hi(0, "MiniHipatterns_262936_bg", { bg = "#262936", fg = "#ffffff" })
hi(0, "MiniHipatterns_274f64_bg", { bg = "#274f64", fg = "#ffffff" })
hi(0, "MiniHipatterns_2d333f_bg", { bg = "#2d333f", fg = "#ffffff" })
hi(0, "MiniHipatterns_313244_bg", { bg = "#313244", fg = "#ffffff" })
hi(0, "MiniHipatterns_31748f_bg", { bg = "#31748f", fg = "#ffffff" })
hi(0, "MiniHipatterns_323449_bg", { bg = "#323449", fg = "#ffffff" })
hi(0, "MiniHipatterns_32363f_bg", { bg = "#32363f", fg = "#ffffff" })
hi(0, "MiniHipatterns_32748f_bg", { bg = "#32748f", fg = "#ffffff" })
hi(0, "MiniHipatterns_332d41_bg", { bg = "#332d41", fg = "#ffffff" })
hi(0, "MiniHipatterns_333c48_bg", { bg = "#333c48", fg = "#ffffff" })
hi(0, "MiniHipatterns_37f499_bg", { bg = "#37f499", fg = "#000000" })
hi(0, "MiniHipatterns_39303b_bg", { bg = "#39303b", fg = "#ffffff" })
hi(0, "MiniHipatterns_3b344b_bg", { bg = "#3b344b", fg = "#ffffff" })
hi(0, "MiniHipatterns_403d52_bg", { bg = "#403d52", fg = "#ffffff" })
hi(0, "MiniHipatterns_43293a_bg", { bg = "#43293a", fg = "#ffffff" })
hi(0, "MiniHipatterns_433842_bg", { bg = "#433842", fg = "#ffffff" })
hi(0, "MiniHipatterns_453935_bg", { bg = "#453935", fg = "#ffffff" })
hi(0, "MiniHipatterns_45475a_bg", { bg = "#45475a", fg = "#ffffff" })
hi(0, "MiniHipatterns_467c7b_bg", { bg = "#467c7b", fg = "#ffffff" })
hi(0, "MiniHipatterns_524f67_bg", { bg = "#524f67", fg = "#ffffff" })
hi(0, "MiniHipatterns_585b70_bg", { bg = "#585b70", fg = "#ffffff" })
hi(0, "MiniHipatterns_597b60_bg", { bg = "#597b60", fg = "#ffffff" })
hi(0, "MiniHipatterns_6d5960_bg", { bg = "#6d5960", fg = "#ffffff" })
hi(0, "MiniHipatterns_6e6a86_bg", { bg = "#6e6a86", fg = "#ffffff" })
hi(0, "MiniHipatterns_7f605c_bg", { bg = "#7f605c", fg = "#ffffff" })
hi(0, "MiniHipatterns_808080_bg", { bg = "#808080", fg = "#000000" })
hi(0, "MiniHipatterns_89b4fa_bg", { bg = "#89b4fa", fg = "#000000" })
hi(0, "MiniHipatterns_8b0000_bg", { bg = "#8b0000", fg = "#ffffff" })
hi(0, "MiniHipatterns_8b008b_bg", { bg = "#8b008b", fg = "#ffffff" })
hi(0, "MiniHipatterns_8c801f_bg", { bg = "#8c801f", fg = "#000000" })
hi(0, "MiniHipatterns_8c8020_bg", { bg = "#8c8020", fg = "#000000" })
hi(0, "MiniHipatterns_8c8021_bg", { bg = "#8c8021", fg = "#000000" })
hi(0, "MiniHipatterns_908caa_bg", { bg = "#908caa", fg = "#000000" })
hi(0, "MiniHipatterns_94e2d5_bg", { bg = "#94e2d5", fg = "#000000" })
hi(0, "MiniHipatterns_95b1ac_bg", { bg = "#95b1ac", fg = "#000000" })
hi(0, "MiniHipatterns_9ccfd8_bg", { bg = "#9ccfd8", fg = "#000000" })
hi(0, "MiniHipatterns_a48cf2_bg", { bg = "#a48cf2", fg = "#000000" })
hi(0, "MiniHipatterns_a6e3a1_bg", { bg = "#a6e3a1", fg = "#000000" })
hi(0, "MiniHipatterns_b4befe_bg", { bg = "#b4befe", fg = "#000000" })
hi(0, "MiniHipatterns_bbbb00_bg", { bg = "#bbbb00", fg = "#000000" })
hi(0, "MiniHipatterns_c4a7e7_bg", { bg = "#c4a7e7", fg = "#000000" })
hi(0, "MiniHipatterns_cba6f7_bg", { bg = "#cba6f7", fg = "#000000" })
hi(0, "MiniHipatterns_cdd6f4_bg", { bg = "#cdd6f4", fg = "#000000" })
hi(0, "MiniHipatterns_e0def4_bg", { bg = "#e0def4", fg = "#000000" })
hi(0, "MiniHipatterns_eb6f92_bg", { bg = "#eb6f92", fg = "#000000" })
hi(0, "MiniHipatterns_ebbcba_bg", { bg = "#ebbcba", fg = "#000000" })
hi(0, "MiniHipatterns_f1fc79_bg", { bg = "#f1fc79", fg = "#000000" })
hi(0, "MiniHipatterns_f265b5_bg", { bg = "#f265b5", fg = "#000000" })
hi(0, "MiniHipatterns_f2cdcd_bg", { bg = "#f2cdcd", fg = "#000000" })
hi(0, "MiniHipatterns_f38ba8_bg", { bg = "#f38ba8", fg = "#000000" })
hi(0, "MiniHipatterns_f5e0dc_bg", { bg = "#f5e0dc", fg = "#000000" })
hi(0, "MiniHipatterns_f6c177_bg", { bg = "#f6c177", fg = "#000000" })
hi(0, "MiniHipatterns_f7c67f_bg", { bg = "#f7c67f", fg = "#000000" })
hi(0, "MiniHipatterns_f9e2af_bg", { bg = "#f9e2af", fg = "#000000" })
hi(0, "MiniHipatterns_fab387_bg", { bg = "#fab387", fg = "#000000" })
hi(0, "MiniHipatterns_ffffff_bg", { bg = "#ffffff", fg = "#000000" })
hi(
  0,
  "MiniJump2dSpot",
  { bg = "#000000", bold = true, fg = "#ffffff", nocombine = true }
)
hi(
  0,
  "MiniJump2dSpotAhead",
  { bg = "#000000", fg = "#808080", nocombine = true }
)
hi(0, "ModeMsg", { fg = "#98c379" })
hi(0, "MoreMsg", { fg = "#98c379" })
hi(0, "NoiceAttr69", { fg = "#fa7883" })
hi(0, "NoiceAttr70", { fg = "#6bb8ff" })
hi(0, "NoiceAttr76", { fg = "#98c379" })
hi(0, "NoiceAttr78", { fg = "#878d96" })
hi(0, "NoiceAttr85", { fg = "#ffffff" })
hi(0, "NoiceFormatProgressDone", { bg = "#ff9470", fg = "#22273d" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#878d96" })
hi(0, "Normal", { bg = "#171726", fg = "#ffffff" })
hi(0, "NormalFloat", { bg = "#171726", fg = "#ffffff" })
hi(0, "NormalNC", { bg = "#171726", fg = "#ffffff" })
hi(0, "NotifyDEBUGBody", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#8af5ff" })
hi(0, "NotifyDEBUGIcon", { fg = "#8af5ff" })
hi(0, "NotifyDEBUGTitle", { fg = "#8af5ff" })
hi(0, "NotifyERRORBody", { link = "Normal" })
hi(0, "NotifyERRORBorder", { fg = "#fa7883" })
hi(0, "NotifyERRORIcon", { fg = "#fa7883" })
hi(0, "NotifyERRORTitle", { fg = "#fa7883" })
hi(0, "NotifyINFOBody", { link = "Normal" })
hi(0, "NotifyINFOBorder", { fg = "#ffffff" })
hi(0, "NotifyINFOIcon", { fg = "#ffffff" })
hi(0, "NotifyINFOTitle", { fg = "#ffffff" })
hi(0, "NotifyTRACEBody", { link = "Normal" })
hi(0, "NotifyTRACEBorder", { fg = "#8af5ff" })
hi(0, "NotifyTRACEIcon", { fg = "#8af5ff" })
hi(0, "NotifyTRACETitle", { fg = "#8af5ff" })
hi(0, "NotifyWARNBody", { link = "Normal" })
hi(0, "NotifyWARNBorder", { fg = "#e799ff" })
hi(0, "NotifyWARNIcon", { fg = "#e799ff" })
hi(0, "NotifyWARNTitle", { fg = "#e799ff" })
hi(0, "Number", { fg = "#ffc387" })
hi(0, "NvimInternalError", { bg = "#fa7883", fg = "#171726" })
hi(0, "Operator", { fg = "#e799ff" })
hi(0, "Pmenu", { bg = "#22273d", fg = "#ffffff" })
hi(0, "PmenuSel", { bg = "#313244" })
hi(0, "PreProc", { fg = "#ff9470" })
hi(0, "Question", { fg = "#6bb8ff" })
hi(0, "QuickFixLine", { bg = "#22273d" })
hi(0, "Repeat", { fg = "#ff9470" })
hi(0, "Search", { bg = "#ff9470", fg = "#22273d" })
hi(0, "SignColumn", {})
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImage1", { fg = "#8c801f", sp = "#000001" })
hi(0, "SnacksImage2", { fg = "#8c8020", sp = "#000002" })
hi(0, "SnacksImage3", { fg = "#8c8021", sp = "#000003" })
hi(0, "SnacksIndent", { fg = "#26233a" })
hi(0, "SnacksIndentBlank", { fg = "#26233a" })
hi(0, "SnacksIndentChunk", { fg = "#26233a" })
hi(0, "SnacksIndentScope", { fg = "#908caa" })
hi(0, "SnacksPickerMatch", { bold = true, fg = "#ebbcba" })
hi(0, "Special", { fg = "#8af5ff" })
hi(0, "SpecialChar", { fg = "#b3684f" })
hi(0, "SpecialKey", { fg = "#878d96" })
hi(0, "SpellBad", { sp = "#fa7883", undercurl = true })
hi(0, "SpellCap", { sp = "#6bb8ff", undercurl = true })
hi(0, "SpellLocal", { sp = "#8af5ff", undercurl = true })
hi(0, "SpellRare", { sp = "#e799ff", undercurl = true })
hi(0, "Statement", { fg = "#fa7883" })
hi(0, "StatusLine", { bg = "#525866", fg = "#ffffff" })
hi(0, "StatusLineNC", { bg = "#22273d", fg = "#c8c8c8" })
hi(0, "StorageClass", { fg = "#ff9470" })
hi(0, "String", { fg = "#98c379" })
hi(0, "Structure", { fg = "#e799ff" })
hi(0, "Substitute", { bg = "#ff9470", fg = "#22273d" })
hi(0, "TSAnnotation", { fg = "#b3684f" })
hi(0, "TSAttribute", { fg = "#ff9470" })
hi(0, "TSBoolean", { fg = "#ffc387" })
hi(0, "TSCharacter", { fg = "#fa7883" })
hi(0, "TSComment", { fg = "#878d96", italic = true })
hi(0, "TSConditional", { fg = "#e799ff" })
hi(0, "TSConstBuiltin", { fg = "#ffc387", italic = true })
hi(0, "TSConstMacro", { fg = "#fa7883" })
hi(0, "TSConstant", { fg = "#ffc387" })
hi(0, "TSConstructor", { fg = "#6bb8ff" })
hi(0, "TSCurrentScope", { bold = true })
hi(0, "TSDefinition", { sp = "#c8c8c8", underline = true })
hi(0, "TSDefinitionUsage", { sp = "#c8c8c8", underline = true })
hi(0, "TSEmphasis", { fg = "#ffc387", italic = true })
hi(0, "TSError", { fg = "#fa7883" })
hi(0, "TSException", { fg = "#fa7883" })
hi(0, "TSField", { fg = "#ffffff" })
hi(0, "TSFloat", { fg = "#ffc387" })
hi(0, "TSFuncBuiltin", { fg = "#6bb8ff", italic = true })
hi(0, "TSFuncMacro", { fg = "#fa7883" })
hi(0, "TSFunction", { fg = "#6bb8ff" })
hi(0, "TSInclude", { fg = "#6bb8ff" })
hi(0, "TSKeyword", { fg = "#e799ff" })
hi(0, "TSKeywordFunction", { fg = "#e799ff" })
hi(0, "TSKeywordOperator", { fg = "#e799ff" })
hi(0, "TSLabel", { fg = "#ff9470" })
hi(0, "TSLiteral", { fg = "#ffc387" })
hi(0, "TSMethod", { fg = "#6bb8ff" })
hi(0, "TSNamespace", { fg = "#fa7883" })
hi(0, "TSNone", { fg = "#ffffff" })
hi(0, "TSNumber", { fg = "#ffc387" })
hi(0, "TSOperator", { fg = "#ffffff" })
hi(0, "TSParameter", { fg = "#ffffff" })
hi(0, "TSParameterReference", { fg = "#ffffff" })
hi(0, "TSProperty", { fg = "#ffffff" })
hi(0, "TSPunctBracket", { fg = "#ffffff" })
hi(0, "TSPunctDelimiter", { fg = "#b3684f" })
hi(0, "TSPunctSpecial", { fg = "#b3684f" })
hi(0, "TSRepeat", { fg = "#e799ff" })
hi(0, "TSStrike", { fg = "#171726", strikethrough = true })
hi(0, "TSString", { fg = "#98c379" })
hi(0, "TSStringEscape", { fg = "#8af5ff" })
hi(0, "TSStringRegex", { fg = "#8af5ff" })
hi(0, "TSStrong", { bold = true })
hi(0, "TSSymbol", { fg = "#98c379" })
hi(0, "TSTag", { fg = "#fa7883" })
hi(0, "TSTagDelimiter", { fg = "#b3684f" })
hi(0, "TSText", { fg = "#ffffff" })
hi(0, "TSTitle", { fg = "#6bb8ff" })
hi(0, "TSType", { fg = "#ff9470" })
hi(0, "TSTypeBuiltin", { fg = "#ff9470", italic = true })
hi(0, "TSURI", { fg = "#ffc387", underline = true })
hi(0, "TSUnderline", { fg = "#171726", underline = true })
hi(0, "TSVariable", { fg = "#fa7883" })
hi(0, "TSVariableBuiltin", { fg = "#fa7883", italic = true })
hi(0, "TabLine", { bg = "#22273d", fg = "#878d96" })
hi(0, "TabLineFill", { bg = "#22273d", fg = "#878d96" })
hi(0, "TabLineSel", { bg = "#22273d", fg = "#98c379" })
hi(0, "Tag", { fg = "#ff9470" })
hi(0, "TelescopeBorder", { bg = "#141422", fg = "#141422" })
hi(0, "TelescopeNormal", { bg = "#141422" })
hi(0, "TelescopePreviewLine", { bg = "#22273d" })
hi(0, "TelescopePreviewTitle", { bg = "#98c379", fg = "#1e2336" })
hi(0, "TelescopePromptBorder", { bg = "#494f5b", fg = "#494f5b" })
hi(0, "TelescopePromptNormal", { bg = "#494f5b", fg = "#ffffff" })
hi(0, "TelescopePromptPrefix", { bg = "#494f5b", fg = "#fa7883" })
hi(0, "TelescopePromptTitle", { bg = "#fa7883", fg = "#1e2336" })
hi(0, "TelescopeResultsTitle", { bg = "#141422", fg = "#141422" })
hi(0, "TelescopeSelection", { bg = "#494f5b" })
hi(0, "TermCursor", { bg = "#ffffff", fg = "#171726" })
hi(0, "TermCursorNC", { bg = "#ffffff", fg = "#171726" })
hi(0, "Title", { fg = "#6bb8ff" })
hi(0, "Todo", { bg = "#22273d", fg = "#ff9470" })
hi(0, "TooLong", { fg = "#fa7883" })
hi(0, "TreesitterContext", { bg = "#22273d", italic = true })
hi(0, "Type", { fg = "#ff9470" })
hi(0, "Typedef", { fg = "#ff9470" })
hi(0, "Underlined", { fg = "#fa7883" })
hi(0, "User1", { bg = "#525866", fg = "#fa7883" })
hi(0, "User2", { bg = "#525866", fg = "#e799ff" })
hi(0, "User3", { bg = "#525866", fg = "#ffffff" })
hi(0, "User4", { bg = "#525866", fg = "#8af5ff" })
hi(0, "User5", { bg = "#525866", fg = "#ffffff" })
hi(0, "User6", { bg = "#22273d", fg = "#ffffff" })
hi(0, "User7", { bg = "#525866", fg = "#ffffff" })
hi(0, "User8", { bg = "#525866", fg = "#171726" })
hi(0, "User9", { bg = "#525866", fg = "#171726" })
hi(0, "VertSplit", { bg = "#171726", fg = "#ffffff" })
hi(0, "Visual", { bg = "#525866" })
hi(0, "VisualNOS", { fg = "#fa7883" })
hi(0, "WarningMsg", { fg = "#fa7883" })
hi(0, "WildMenu", { bg = "#ff9470", fg = "#fa7883" })
hi(0, "WinBar", { fg = "#ffffff" })
hi(0, "WinBarNC", { fg = "#c8c8c8" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ffc387" })
hi(0, "gitcommitComment", { fg = "#878d96" })
hi(0, "gitcommitDiscarded", { fg = "#878d96" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#fa7883" })
hi(0, "gitcommitDiscardedType", { fg = "#6bb8ff" })
hi(0, "gitcommitHeader", { fg = "#e799ff" })
hi(0, "gitcommitOverflow", { fg = "#fa7883" })
hi(0, "gitcommitSelected", { fg = "#878d96" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#98c379" })
hi(0, "gitcommitSelectedType", { fg = "#6bb8ff" })
hi(0, "gitcommitSummary", { fg = "#98c379" })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = "#fa7883" })
hi(0, "gitcommitUnmergedType", { fg = "#6bb8ff" })
hi(0, "gitcommitUntracked", { fg = "#878d96" })
hi(0, "gitcommitUntrackedFile", { fg = "#ff9470" })
hi(0, "lCursor", { bg = "#ffffff", fg = "#171726" })
hi(0, "rainbowcol1", { fg = "#ffffff" })
hi(0, "rainbowcol2", { fg = "#ffc387" })
hi(0, "rainbowcol3", { fg = "#ff9470" })
hi(0, "rainbowcol4", { fg = "#ffffff" })
hi(0, "rainbowcol5", { fg = "#8af5ff" })
hi(0, "rainbowcol6", { fg = "#6bb8ff" })
hi(0, "rainbowcol7", { fg = "#e799ff" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#171726"
g.terminal_color_1 = "#fa7883"
g.terminal_color_2 = "#98c379"
g.terminal_color_3 = "#ff9470"
g.terminal_color_4 = "#6bb8ff"
g.terminal_color_5 = "#e799ff"
g.terminal_color_6 = "#8af5ff"
g.terminal_color_7 = "#ffffff"
g.terminal_color_8 = "#878d96"
g.terminal_color_9 = "#fa7883"
g.terminal_color_10 = "#98c379"
g.terminal_color_11 = "#ff9470"
g.terminal_color_12 = "#6bb8ff"
g.terminal_color_13 = "#e799ff"
g.terminal_color_14 = "#8af5ff"
g.terminal_color_15 = "#ffffff"
