-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd("highlight clear")
end
vim.g.colors_name = "rose-pine"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#c4a7e7" })
hi(0, "@attribute.builtin", { bold = true, fg = "#c4a7e7" })
hi(0, "@attribute.diff", { fg = "#f6c177" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@class", { fg = "#9ccfd8" })
hi(0, "@comment.error", { fg = "#eb6f92" })
hi(0, "@comment.hint", { bg = "#332d41", fg = "#c4a7e7" })
hi(0, "@comment.info", { bg = "#2d333f", fg = "#9ccfd8" })
hi(0, "@comment.note", { bg = "#1d2534", fg = "#31748f" })
hi(0, "@comment.todo", { bg = "#39303b", fg = "#ebbcba" })
hi(0, "@comment.warning", { fg = "#f6c177" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@conceal.markdown", { fg = "#908caa" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant", { fg = "#f6c177" })
hi(0, "@constant.builtin", { bold = true, fg = "#f6c177" })
hi(0, "@constant.macro", { fg = "#f6c177" })
hi(0, "@constructor", { fg = "#9ccfd8" })
hi(0, "@diff.delta", { bg = "#433842" })
hi(0, "@diff.minus", { bg = "#43293a", fg = "#eb6f92" })
hi(0, "@diff.plus", { bg = "#333c48", fg = "#9ccfd8" })
hi(0, "@field", { fg = "#9ccfd8" })
hi(0, "@float", { link = "Number" })
hi(0, "@function", { fg = "#ebbcba" })
hi(0, "@function.builtin", { bold = true, fg = "#ebbcba" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { fg = "#ebbcba" })
hi(0, "@function.method.call", { fg = "#c4a7e7" })
hi(0, "@include", { link = "Include" })
hi(0, "@interface", { fg = "#9ccfd8" })
hi(0, "@keyword.conditional", { fg = "#31748f" })
hi(0, "@keyword.conditional.ternary", { fg = "#31748f" })
hi(0, "@keyword.debug", { fg = "#ebbcba" })
hi(0, "@keyword.directive", { fg = "#c4a7e7" })
hi(0, "@keyword.directive.define", { fg = "#c4a7e7" })
hi(0, "@keyword.exception", { fg = "#31748f" })
hi(0, "@keyword.import", { fg = "#31748f" })
hi(0, "@keyword.operator", { fg = "#908caa" })
hi(0, "@keyword.repeat", { fg = "#31748f" })
hi(0, "@keyword.return", { fg = "#31748f" })
hi(0, "@keyword.storage", { fg = "#9ccfd8" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.comment.c", { link = "@comment" })
hi(0, "@lsp.type.comment.cpp", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.svelte", { link = "@variable" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "@type" })
hi(0, "@markup.heading", { bold = true, fg = "#9ccfd8" })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#9ccfd8" })
hi(0, "@markup.link.markdown_inline", { fg = "#908caa" })
hi(0, "@markup.link.url", { fg = "#c4a7e7" })
hi(0, "@markup.list", { fg = "#31748f" })
hi(0, "@markup.list.checked", { bg = "#262936", fg = "#9ccfd8" })
hi(0, "@markup.list.unchecked", { fg = "#e0def4" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { fg = "#e0def4" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#908caa" })
hi(0, "@markup.raw.markdown_inline", { fg = "#f6c177" })
hi(0, "@method", { fg = "#ebbcba" })
hi(0, "@module", { fg = "#e0def4" })
hi(0, "@module.builtin", { bold = true, fg = "#e0def4" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number.float", { link = "Number" })
hi(0, "@parameter", { fg = "#c4a7e7", italic = true })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#9ccfd8", italic = true })
hi(0, "@punctuation", { fg = "#908caa" })
hi(0, "@punctuation.bracket", { fg = "#908caa" })
hi(0, "@punctuation.delimiter", { fg = "#908caa" })
hi(0, "@punctuation.special", { fg = "#908caa" })
hi(0, "@regexp", { link = "String" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#31748f" })
hi(0, "@string.regexp", { fg = "#c4a7e7" })
hi(0, "@string.special", { link = "String" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { fg = "#c4a7e7" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { fg = "#c4a7e7" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#908caa" })
hi(0, "@text", { fg = "#e0def4" })
hi(0, "@text.danger", { fg = "#eb6f92" })
hi(0, "@text.diff.add", { bg = "#333c48", fg = "#9ccfd8" })
hi(0, "@text.diff.delete", { bg = "#43293a", fg = "#eb6f92" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#c4a7e7" })
hi(0, "@text.warning", { fg = "#f6c177" })
hi(0, "@todo", { link = "Todo" })
hi(0, "@type", { fg = "#9ccfd8" })
hi(0, "@type.builtin", { bold = true, fg = "#9ccfd8" })
hi(0, "@variable", { fg = "#e0def4", italic = true })
hi(0, "@variable.builtin", { bold = true, fg = "#eb6f92", italic = true })
hi(0, "@variable.member", { fg = "#9ccfd8" })
hi(0, "@variable.parameter", { fg = "#c4a7e7", italic = true })
hi(
  0,
  "@variable.parameter.builtin",
  { bold = true, fg = "#c4a7e7", italic = true }
)
hi(0, "AlphaButtons", { fg = "#9ccfd8" })
hi(0, "AlphaFooter", { fg = "#f6c177" })
hi(0, "AlphaHeader", { fg = "#31748f" })
hi(0, "AlphaShortcut", { fg = "#ebbcba" })
hi(0, "AvanteReversedSubtitle", { fg = "#9ccfd8" })
hi(0, "AvanteReversedThirdTitle", { fg = "#c4a7e7" })
hi(0, "AvanteReversedTitle", { fg = "#ebbcba" })
hi(0, "AvanteSubtitle", { bg = "#9ccfd8", fg = "#403d52" })
hi(0, "AvanteThirdTitle", { bg = "#c4a7e7", fg = "#403d52" })
hi(0, "AvanteTitle", { bg = "#ebbcba", fg = "#524f67" })
hi(0, "BlinkCmpDefault", { fg = "#403d52" })
hi(0, "BlinkCmpDoc", { fg = "#e0def4" })
hi(0, "BlinkCmpDocBorder", { fg = "#524f67" })
hi(0, "BlinkCmpGhostText", { fg = "#6e6a86" })
hi(0, "BlinkCmpKindClass", { fg = "#f6c177" })
hi(0, "BlinkCmpKindCodeium", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindColor", { fg = "#eb6f92" })
hi(0, "BlinkCmpKindConstant", { fg = "#f6c177" })
hi(0, "BlinkCmpKindConstructor", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindCopilot", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindEnum", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindEnumMember", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindEvent", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindField", { fg = "#31748f" })
hi(0, "BlinkCmpKindFile", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindFolder", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindFunction", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindInterface", { fg = "#f6c177" })
hi(0, "BlinkCmpKindKeyword", { fg = "#c4a7e7" })
hi(0, "BlinkCmpKindMethod", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindModule", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindOperator", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindProperty", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindReference", { fg = "#eb6f92" })
hi(0, "BlinkCmpKindSnippet", { fg = "#ebbcba" })
hi(0, "BlinkCmpKindStruct", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindTabNine", { fg = "#9ccfd8" })
hi(0, "BlinkCmpKindText", { fg = "#31748f" })
hi(0, "BlinkCmpKindTypeParameter", { fg = "#c4a7e7" })
hi(0, "BlinkCmpKindUnit", { fg = "#31748f" })
hi(0, "BlinkCmpKindValue", { fg = "#eb6f92" })
hi(0, "BlinkCmpKindVariable", { fg = "#ebbcba" })
hi(0, "BlinkCmpLabel", { fg = "#6e6a86" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#6e6a86", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#e0def4" })
hi(0, "Boolean", { fg = "#ebbcba" })
hi(0, "BufferCurrent", { bg = "#26233a", fg = "#e0def4" })
hi(0, "BufferCurrentIndex", { bg = "#26233a", fg = "#e0def4" })
hi(0, "BufferCurrentMod", { bg = "#26233a", fg = "#9ccfd8" })
hi(0, "BufferCurrentSign", { bg = "#26233a", fg = "#908caa" })
hi(0, "BufferCurrentTarget", { bg = "#26233a", fg = "#f6c177" })
hi(0, "BufferInactive", { fg = "#908caa" })
hi(0, "BufferInactiveIndex", { fg = "#908caa" })
hi(0, "BufferInactiveMod", { fg = "#9ccfd8" })
hi(0, "BufferInactiveSign", { fg = "#6e6a86" })
hi(0, "BufferInactiveTarget", { fg = "#f6c177" })
hi(0, "BufferVisible", { fg = "#908caa" })
hi(0, "BufferVisibleIndex", { fg = "#908caa" })
hi(0, "BufferVisibleMod", { fg = "#9ccfd8" })
hi(0, "BufferVisibleSign", { fg = "#6e6a86" })
hi(0, "BufferVisibleTarget", { fg = "#f6c177" })
hi(0, "Character", { fg = "#f6c177" })
hi(0, "CmpItemAbbr", { fg = "#908caa" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#908caa", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e0def4" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e0def4" })
hi(0, "CmpItemKind", { fg = "#908caa" })
hi(0, "CmpItemKindClass", { link = "StorageClass" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindMethod", { link = "PreProc" })
hi(0, "CmpItemKindSnippet", { link = "String" })
hi(0, "CmpItemKindVariable", { link = "Identifier" })
hi(0, "ColorColumn", { bg = "#1f1d2e" })
hi(0, "Comment", { fg = "#908caa", italic = true })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#31748f" })
hi(0, "Constant", { fg = "#f6c177" })
hi(0, "CopilotSuggestion", { fg = "#6e6a86", italic = true })
hi(0, "CurSearch", { bg = "#f6c177", fg = "#191724" })
hi(0, "Cursor", { bg = "#524f67", fg = "#e0def4" })
hi(0, "CursorColumn", { bg = "#26233a" })
hi(0, "CursorLine", { bg = "#26233a" })
hi(0, "CursorLineNr", { bold = true, fg = "#e0def4" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#f6c177" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#6e6a86" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#9ccfd8" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { fg = "#6e6a86" })
hi(0, "DapUIFrameName", { fg = "#e0def4" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#9ccfd8" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#c4a7e7" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#f6c177" })
hi(0, "DapUIValue", { fg = "#e0def4" })
hi(0, "DapUIVariable", { fg = "#e0def4" })
hi(0, "DapUIWatchesEmpty", { fg = "#eb6f92" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DashboardCenter", { fg = "#f6c177" })
hi(0, "DashboardFooter", { fg = "#c4a7e7" })
hi(0, "DashboardHeader", { fg = "#31748f" })
hi(0, "DashboardShortcut", { fg = "#eb6f92" })
hi(0, "Debug", { fg = "#ebbcba" })
hi(0, "Define", { fg = "#c4a7e7" })
hi(0, "DefinitionCount", { fg = "#ebbcba" })
hi(0, "DefinitionIcon", { fg = "#ebbcba" })
hi(0, "DefinitionPreviewTitle", { bold = true, fg = "#ebbcba" })
hi(0, "Delimiter", { fg = "#908caa" })
hi(0, "DiagnosticDefaultError", { link = "DiagnosticError" })
hi(0, "DiagnosticDefaultHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticDefaultInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticDefaultOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticDefaultWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticError", { fg = "#eb6f92" })
hi(0, "DiagnosticHint", { fg = "#c4a7e7" })
hi(0, "DiagnosticInfo", { fg = "#9ccfd8" })
hi(0, "DiagnosticOk", { fg = "#95b1ac" })
hi(0, "DiagnosticUnderlineError", { sp = "#eb6f92" })
hi(0, "DiagnosticUnderlineHint", { sp = "#c4a7e7" })
hi(0, "DiagnosticUnderlineInfo", { sp = "#9ccfd8" })
hi(0, "DiagnosticUnderlineOk", { sp = "#95b1ac" })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f6c177" })
hi(0, "DiagnosticVirtualTextError", { fg = "#eb6f92" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#c4a7e7" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#9ccfd8" })
hi(0, "DiagnosticVirtualTextOk", { fg = "#95b1ac" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#f6c177" })
hi(0, "DiagnosticWarn", { fg = "#f6c177" })
hi(0, "DiffAdd", { bg = "#333c48" })
hi(0, "DiffChange", { bg = "#433842" })
hi(0, "DiffDelete", { bg = "#43293a" })
hi(0, "DiffText", { bg = "#6d5960" })
hi(0, "Directory", { bold = true, fg = "#9ccfd8" })
hi(0, "Error", { fg = "#eb6f92" })
hi(0, "ErrorMsg", { bold = true, fg = "#eb6f92" })
hi(0, "Exception", { fg = "#31748f" })
hi(0, "FlashLabel", { bg = "#eb6f92", fg = "#191724" })
hi(0, "Float", { fg = "#f6c177" })
hi(0, "FloatBorder", { fg = "#6e6a86" })
hi(0, "FloatTitle", { bold = true, fg = "#9ccfd8" })
hi(0, "FoldColumn", { fg = "#6e6a86" })
hi(0, "Folded", { fg = "#e0def4" })
hi(0, "Function", { fg = "#ebbcba" })
hi(0, "FzfLuaBorder", { fg = "#6e6a86" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#908caa" })
hi(0, "FzfLuaBufFlagCur", { fg = "#908caa" })
hi(0, "FzfLuaCursorLine", { bg = "#26233a", fg = "#e0def4" })
hi(0, "FzfLuaFilePart", { fg = "#e0def4" })
hi(0, "FzfLuaHeaderBind", { fg = "#ebbcba" })
hi(0, "FzfLuaHeaderText", { fg = "#eb6f92" })
hi(0, "FzfLuaNormal", { link = "NormalFloat" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddCul", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { bg = "#333c48" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#433842" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#433842" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedUntracked", { fg = "#597b60" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#597b60" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#333c48" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#597b60" })
hi(0, "GrugFarHelpHeader", { fg = "#31748f" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#f6c177" })
hi(0, "GrugFarHelpWinActionKey", { fg = "#f6c177" })
hi(0, "GrugFarHelpWinActionPrefix", { fg = "#9ccfd8" })
hi(0, "GrugFarHelpWinActionText", { fg = "#31748f" })
hi(0, "GrugFarHelpWinHeader", { link = "FloatTitle" })
hi(0, "GrugFarInputLabel", { fg = "#9ccfd8" })
hi(0, "GrugFarInputPlaceholder", { link = "Comment" })
hi(0, "GrugFarResultsActionMessage", { fg = "#9ccfd8" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#ebbcba" })
hi(0, "GrugFarResultsHeader", { fg = "#31748f" })
hi(0, "GrugFarResultsLineColumn", { link = "GrugFarResultsLineNo" })
hi(0, "GrugFarResultsLineNo", { fg = "#c4a7e7" })
hi(0, "GrugFarResultsMatch", { link = "CurSearch" })
hi(0, "GrugFarResultsPath", { fg = "#9ccfd8" })
hi(0, "GrugFarResultsStats", { fg = "#c4a7e7" })
hi(0, "Headline1Bg", { bg = "#323449", fg = "#f265b5" })
hi(0, "Headline1Fg", { bold = true, fg = "#f265b5" })
hi(0, "Headline2Bg", { bg = "#323449", fg = "#37f499" })
hi(0, "Headline2Fg", { bold = true, fg = "#37f499" })
hi(0, "Headline3Bg", { bg = "#323449", fg = "#04d1f9" })
hi(0, "Headline3Fg", { bold = true, fg = "#04d1f9" })
hi(0, "Headline4Bg", { bg = "#323449", fg = "#a48cf2" })
hi(0, "Headline4Fg", { bold = true, fg = "#a48cf2" })
hi(0, "Headline5Bg", { bg = "#323449", fg = "#f1fc79" })
hi(0, "Headline5Fg", { bold = true, fg = "#f1fc79" })
hi(0, "Headline6Bg", { bg = "#323449", fg = "#f7c67f" })
hi(0, "Headline6Fg", { bold = true, fg = "#f7c67f" })
hi(0, "HopNextKey", { bg = "#43293a", fg = "#eb6f92" })
hi(0, "HopNextKey1", { bg = "#333c48", fg = "#9ccfd8" })
hi(0, "HopNextKey2", { bg = "#1e2a39", fg = "#31748f" })
hi(0, "HopUnmatched", { fg = "#6e6a86" })
hi(0, "IblIndent", { fg = "#26233a" })
hi(0, "IblScope", { fg = "#9ccfd8" })
hi(0, "IblWhitespace", { fg = "#26233a" })
hi(0, "Identifier", { fg = "#e0def4" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "Include", { fg = "#31748f" })
hi(0, "IndentBlanklineChar", { fg = "#6e6a86", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#6e6a86", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#6e6a86", nocombine = true })
hi(0, "Keyword", { fg = "#31748f" })
hi(0, "Label", { fg = "#9ccfd8" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { link = "StatusLineTerm" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#cdd6f4" })
hi(0, "LineNrAbove", { fg = "#585b70" })
hi(0, "LineNrBelow", { fg = "#585b70" })
hi(0, "LspCodeLens", { fg = "#908caa" })
hi(0, "LspCodeLensSeparator", { fg = "#6e6a86" })
hi(0, "LspFloatWinBorder", { fg = "#6e6a86" })
hi(0, "LspFloatWinNormal", { bg = "#1f1d2e" })
hi(0, "LspInlayHint", { bg = "#221f2e", fg = "#6e6a86" })
hi(0, "LspReferenceRead", { bg = "#403d52" })
hi(0, "LspReferenceText", { bg = "#403d52" })
hi(0, "LspReferenceWrite", { bg = "#403d52" })
hi(0, "LspSagaAutoPreview", { fg = "#908caa" })
hi(0, "LspSagaCodeActionBorder", { fg = "#ebbcba" })
hi(0, "LspSagaCodeActionContent", { fg = "#9ccfd8" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#f6c177" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#6e6a86" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#f6c177" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#9ccfd8" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#f6c177" })
hi(0, "LspSagaHoverBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaLspFinderBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaRenameBorder", { fg = "#31748f" })
hi(0, "LspSagaRenamePromptPrefix", { fg = "#eb6f92" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#9ccfd8" })
hi(0, "LspSignatureActiveParameter", { bg = "#26233a" })
hi(0, "Macro", { fg = "#c4a7e7" })
hi(0, "MatchParen", { bg = "#1f2e3f", fg = "#31748f" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#1f1d2e", bold = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { fg = "#9ccfd8" })
hi(0, "MiniDepsChangeRemoved", { fg = "#eb6f92" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { bg = "#333c48", fg = "#9ccfd8" })
hi(0, "MiniDiffOverChange", { bg = "#433842", fg = "#ebbcba" })
hi(0, "MiniDiffOverContext", { bg = "#1f1d2e" })
hi(0, "MiniDiffOverDelete", { bg = "#43293a", fg = "#eb6f92" })
hi(0, "MiniDiffSignAdd", { fg = "#9ccfd8" })
hi(0, "MiniDiffSignChange", { fg = "#ebbcba" })
hi(0, "MiniDiffSignDelete", { fg = "#eb6f92" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#e0def4" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#ebbcba" })
hi(0, "MiniHipatternsFixme", { bg = "#eb6f92", bold = true, fg = "#191724" })
hi(0, "MiniHipatternsHack", { bg = "#f6c177", bold = true, fg = "#191724" })
hi(0, "MiniHipatternsNote", { bg = "#9ccfd8", bold = true, fg = "#191724" })
hi(0, "MiniHipatternsTodo", { bg = "#c4a7e7", bold = true, fg = "#191724" })
hi(0, "MiniHipatterns_181825_bg", { bg = "#181825", fg = "#ffffff" })
hi(0, "MiniHipatterns_191724_bg", { bg = "#191724", fg = "#ffffff" })
hi(0, "MiniHipatterns_1e1e2e_bg", { bg = "#1e1e2e", fg = "#ffffff" })
hi(0, "MiniHipatterns_1f1d2e_bg", { bg = "#1f1d2e", fg = "#ffffff" })
hi(0, "MiniHipatterns_26233a_bg", { bg = "#26233a", fg = "#ffffff" })
hi(0, "MiniHipatterns_313244_bg", { bg = "#313244", fg = "#ffffff" })
hi(0, "MiniHipatterns_31748f_bg", { bg = "#31748f", fg = "#ffffff" })
hi(0, "MiniHipatterns_45475a_bg", { bg = "#45475a", fg = "#ffffff" })
hi(0, "MiniHipatterns_524f67_bg", { bg = "#524f67", fg = "#ffffff" })
hi(0, "MiniHipatterns_585b70_bg", { bg = "#585b70", fg = "#ffffff" })
hi(0, "MiniHipatterns_6e6a86_bg", { bg = "#6e6a86", fg = "#ffffff" })
hi(0, "MiniHipatterns_89b4fa_bg", { bg = "#89b4fa", fg = "#000000" })
hi(0, "MiniHipatterns_908caa_bg", { bg = "#908caa", fg = "#000000" })
hi(0, "MiniHipatterns_94e2d5_bg", { bg = "#94e2d5", fg = "#000000" })
hi(0, "MiniHipatterns_9ccfd8_bg", { bg = "#9ccfd8", fg = "#000000" })
hi(0, "MiniHipatterns_a6e3a1_bg", { bg = "#a6e3a1", fg = "#000000" })
hi(0, "MiniHipatterns_b4befe_bg", { bg = "#b4befe", fg = "#000000" })
hi(0, "MiniHipatterns_c4a7e7_bg", { bg = "#c4a7e7", fg = "#000000" })
hi(0, "MiniHipatterns_cba6f7_bg", { bg = "#cba6f7", fg = "#000000" })
hi(0, "MiniHipatterns_cdd6f4_bg", { bg = "#cdd6f4", fg = "#000000" })
hi(0, "MiniHipatterns_e0def4_bg", { bg = "#e0def4", fg = "#000000" })
hi(0, "MiniHipatterns_eb6f92_bg", { bg = "#eb6f92", fg = "#000000" })
hi(0, "MiniHipatterns_ebbcba_bg", { bg = "#ebbcba", fg = "#000000" })
hi(0, "MiniHipatterns_f2cdcd_bg", { bg = "#f2cdcd", fg = "#000000" })
hi(0, "MiniHipatterns_f38ba8_bg", { bg = "#f38ba8", fg = "#000000" })
hi(0, "MiniHipatterns_f5e0dc_bg", { bg = "#f5e0dc", fg = "#000000" })
hi(0, "MiniHipatterns_f6c177_bg", { bg = "#f6c177", fg = "#000000" })
hi(0, "MiniHipatterns_f9e2af_bg", { bg = "#f9e2af", fg = "#000000" })
hi(0, "MiniHipatterns_fab387_bg", { bg = "#fab387", fg = "#000000" })
hi(0, "MiniIconsAzure", { fg = "#9ccfd8" })
hi(0, "MiniIconsBlue", { fg = "#31748f" })
hi(0, "MiniIconsCyan", { fg = "#9ccfd8" })
hi(0, "MiniIconsGreen", { fg = "#95b1ac" })
hi(0, "MiniIconsGrey", { fg = "#908caa" })
hi(0, "MiniIconsOrange", { fg = "#ebbcba" })
hi(0, "MiniIconsPurple", { fg = "#c4a7e7" })
hi(0, "MiniIconsRed", { fg = "#eb6f92" })
hi(0, "MiniIconsYellow", { fg = "#f6c177" })
hi(0, "MiniIndentscopeSymbol", { fg = "#6e6a86" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#f6c177" })
hi(0, "MiniJump", { sp = "#f6c177" })
hi(0, "MiniJump2dDim", { fg = "#908caa" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#f6c177", nocombine = true })
hi(
  0,
  "MiniJump2dSpotAhead",
  { bg = "#1f1d2e", fg = "#9ccfd8", nocombine = true }
)
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#ebbcba", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { fg = "#9ccfd8" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bold = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#908caa" })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Delimiter" })
hi(0, "MiniStarterItemPrefix", { link = "WarningMsg" })
hi(0, "MiniStarterQuery", { link = "MoreMsg" })
hi(0, "MiniStarterSection", { fg = "#ebbcba" })
hi(0, "MiniStatuslineDevinfo", { bg = "#26233a", fg = "#908caa" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#1f1d2e", fg = "#6e6a86" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(
  0,
  "MiniStatuslineModeCommand",
  { bg = "#eb6f92", bold = true, fg = "#191724" }
)
hi(
  0,
  "MiniStatuslineModeInsert",
  { bg = "#9ccfd8", bold = true, fg = "#191724" }
)
hi(
  0,
  "MiniStatuslineModeNormal",
  { bg = "#ebbcba", bold = true, fg = "#191724" }
)
hi(
  0,
  "MiniStatuslineModeOther",
  { bg = "#ebbcba", bold = true, fg = "#191724" }
)
hi(
  0,
  "MiniStatuslineModeReplace",
  { bg = "#31748f", bold = true, fg = "#191724" }
)
hi(
  0,
  "MiniStatuslineModeVisual",
  { bg = "#c4a7e7", bold = true, fg = "#191724" }
)
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#26233a", bold = true, fg = "#e0def4" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#1f1d2e", fg = "#908caa" })
hi(
  0,
  "MiniTablineModifiedCurrent",
  { bg = "#e0def4", bold = true, fg = "#26233a" }
)
hi(0, "MiniTablineModifiedHidden", { bg = "#908caa", fg = "#1f1d2e" })
hi(0, "MiniTablineModifiedVisible", { bg = "#e0def4", fg = "#1f1d2e" })
hi(0, "MiniTablineTabpagesection", { link = "Search" })
hi(0, "MiniTablineVisible", { bg = "#1f1d2e", fg = "#e0def4" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#eb6f92" })
hi(0, "MiniTestPass", { bold = true, fg = "#9ccfd8" })
hi(0, "MiniTrailspace", { bg = "#eb6f92" })
hi(0, "ModeMsg", { fg = "#908caa" })
hi(0, "ModesCopy", { bg = "#f6c177" })
hi(0, "ModesDelete", { bg = "#eb6f92" })
hi(0, "ModesInsert", { bg = "#9ccfd8" })
hi(0, "ModesReplace", { bg = "#31748f" })
hi(0, "ModesVisual", { bg = "#c4a7e7" })
hi(0, "MoreMsg", { fg = "#c4a7e7" })
hi(0, "NavicIconsArray", { fg = "#f6c177" })
hi(0, "NavicIconsBoolean", { fg = "#ebbcba" })
hi(0, "NavicIconsClass", { fg = "#9ccfd8" })
hi(0, "NavicIconsConstant", { fg = "#f6c177" })
hi(0, "NavicIconsConstructor", { fg = "#f6c177" })
hi(0, "NavicIconsEnum", { fg = "#f6c177" })
hi(0, "NavicIconsEnumMember", { fg = "#9ccfd8" })
hi(0, "NavicIconsEvent", { fg = "#f6c177" })
hi(0, "NavicIconsField", { fg = "#9ccfd8" })
hi(0, "NavicIconsFile", { fg = "#6e6a86" })
hi(0, "NavicIconsFunction", { fg = "#31748f" })
hi(0, "NavicIconsInterface", { fg = "#9ccfd8" })
hi(0, "NavicIconsKey", { fg = "#c4a7e7" })
hi(0, "NavicIconsKeyword", { fg = "#31748f" })
hi(0, "NavicIconsMethod", { fg = "#c4a7e7" })
hi(0, "NavicIconsModule", { fg = "#ebbcba" })
hi(0, "NavicIconsNamespace", { fg = "#6e6a86" })
hi(0, "NavicIconsNull", { fg = "#eb6f92" })
hi(0, "NavicIconsNumber", { fg = "#f6c177" })
hi(0, "NavicIconsObject", { fg = "#f6c177" })
hi(0, "NavicIconsOperator", { fg = "#908caa" })
hi(0, "NavicIconsPackage", { fg = "#6e6a86" })
hi(0, "NavicIconsProperty", { fg = "#9ccfd8" })
hi(0, "NavicIconsString", { fg = "#f6c177" })
hi(0, "NavicIconsStruct", { fg = "#9ccfd8" })
hi(0, "NavicIconsTypeParameter", { fg = "#9ccfd8" })
hi(0, "NavicIconsVariable", { fg = "#e0def4" })
hi(0, "NavicSeparator", { fg = "#908caa" })
hi(0, "NavicText", { fg = "#908caa" })
hi(0, "NeoTreeGitAdded", { fg = "#9ccfd8" })
hi(0, "NeoTreeGitConflict", { fg = "#c4a7e7" })
hi(0, "NeoTreeGitDeleted", { fg = "#eb6f92" })
hi(0, "NeoTreeGitIgnored", { fg = "#6e6a86" })
hi(0, "NeoTreeGitModified", { fg = "#ebbcba" })
hi(0, "NeoTreeGitRenamed", { fg = "#31748f" })
hi(0, "NeoTreeGitUntracked", { fg = "#908caa" })
hi(0, "NeoTreeTabActive", { bg = "#26233a", fg = "#e0def4" })
hi(0, "NeoTreeTabInactive", { fg = "#908caa" })
hi(0, "NeoTreeTabSeparatorActive", { link = "WinSeparator" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "WinSeparator" })
hi(0, "NeoTreeTitleBar", { link = "StatusLineTerm" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#9ccfd8", italic = true })
hi(
  0,
  "NeogitChangeBothModified",
  { bold = true, fg = "#ebbcba", italic = true }
)
hi(0, "NeogitChangeCopied", { bold = true, fg = "#908caa", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#eb6f92", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#ebbcba", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#c4a7e7", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#31748f", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#ebbcba", italic = true })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffContextHighlight", { bg = "#1f1d2e" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFilePath", { fg = "#9ccfd8", italic = true })
hi(0, "NeogitHunkHeader", { bg = "#1f1d2e" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#1f1d2e" })
hi(0, "NeorgHeading1Prefix", { link = "markdownH1Delimiter" })
hi(0, "NeorgHeading1Title", { link = "markdownH1" })
hi(0, "NeorgHeading2Prefix", { link = "markdownH2Delimiter" })
hi(0, "NeorgHeading2Title", { link = "markdownH2" })
hi(0, "NeorgHeading3Prefix", { link = "markdownH3Delimiter" })
hi(0, "NeorgHeading3Title", { link = "markdownH3" })
hi(0, "NeorgHeading4Prefix", { link = "markdownH4Delimiter" })
hi(0, "NeorgHeading4Title", { link = "markdownH4" })
hi(0, "NeorgHeading5Prefix", { link = "markdownH5Delimiter" })
hi(0, "NeorgHeading5Title", { link = "markdownH5" })
hi(0, "NeorgHeading6Prefix", { link = "markdownH6Delimiter" })
hi(0, "NeorgHeading6Title", { link = "markdownH6" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#9ccfd8" })
hi(0, "NeotestAdapterName", { fg = "#c4a7e7" })
hi(0, "NeotestBorder", { fg = "#403d52" })
hi(0, "NeotestDir", { fg = "#9ccfd8" })
hi(0, "NeotestExpandMarker", { fg = "#403d52" })
hi(0, "NeotestFailed", { fg = "#eb6f92" })
hi(0, "NeotestFile", { fg = "#e0def4" })
hi(0, "NeotestFocused", { bg = "#403d52", fg = "#f6c177" })
hi(0, "NeotestIndent", { fg = "#403d52" })
hi(0, "NeotestMarked", { bold = true, fg = "#ebbcba" })
hi(0, "NeotestNamespace", { fg = "#f6c177" })
hi(0, "NeotestPassed", { fg = "#31748f" })
hi(0, "NeotestRunning", { fg = "#f6c177" })
hi(0, "NeotestSkipped", { fg = "#908caa" })
hi(0, "NeotestTarget", { fg = "#eb6f92" })
hi(0, "NeotestTest", { fg = "#f6c177" })
hi(0, "NeotestUnknown", { fg = "#908caa" })
hi(0, "NeotestWatching", { fg = "#c4a7e7" })
hi(0, "NeotestWinSelect", { fg = "#6e6a86" })
hi(0, "NoiceCursor", { bg = "#e0def4", fg = "#524f67" })
hi(0, "NonText", { fg = "#6e6a86" })
hi(0, "Normal", { fg = "#e0def4" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#e0def4" })
hi(0, "NotifyBackground", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBody", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBorder", { fg = "#6e6a86" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#6e6a86" })
hi(0, "NotifyERRORBody", { link = "NormalFloat" })
hi(0, "NotifyERRORBorder", { fg = "#eb6f92" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#eb6f92" })
hi(0, "NotifyINFOBody", { link = "NormalFloat" })
hi(0, "NotifyINFOBorder", { fg = "#9ccfd8" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#9ccfd8" })
hi(0, "NotifyTRACEBody", { link = "NormalFloat" })
hi(0, "NotifyTRACEBorder", { fg = "#c4a7e7" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#c4a7e7" })
hi(0, "NotifyWARNBody", { link = "NormalFloat" })
hi(0, "NotifyWARNBorder", { fg = "#f6c177" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#f6c177" })
hi(0, "Number", { fg = "#f6c177" })
hi(0, "NvimInternalError", { link = "ErrorMsg" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#6e6a86" })
hi(0, "NvimTreeFileDeleted", { fg = "#eb6f92" })
hi(0, "NvimTreeFileDirty", { fg = "#ebbcba" })
hi(0, "NvimTreeFileMerge", { fg = "#c4a7e7" })
hi(0, "NvimTreeFileNew", { fg = "#9ccfd8" })
hi(0, "NvimTreeFileRenamed", { fg = "#31748f" })
hi(0, "NvimTreeFileStaged", { fg = "#c4a7e7" })
hi(0, "NvimTreeFolderIcon", { fg = "#908caa" })
hi(0, "NvimTreeFolderName", { fg = "#9ccfd8" })
hi(0, "NvimTreeGitDeleted", { fg = "#eb6f92" })
hi(0, "NvimTreeGitDirty", { fg = "#ebbcba" })
hi(0, "NvimTreeGitIgnored", { fg = "#6e6a86" })
hi(0, "NvimTreeGitMerge", { fg = "#c4a7e7" })
hi(0, "NvimTreeGitNew", { fg = "#9ccfd8" })
hi(0, "NvimTreeGitRenamed", { fg = "#31748f" })
hi(0, "NvimTreeGitStaged", { fg = "#c4a7e7" })
hi(0, "NvimTreeImageFile", { fg = "#e0def4" })
hi(0, "NvimTreeNormal", { link = "Normal" })
hi(0, "NvimTreeOpenedFile", { bg = "#26233a", fg = "#e0def4" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#9ccfd8" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { link = "StatusLineTerm" })
hi(0, "Operator", { fg = "#908caa" })
hi(0, "Pmenu", { fg = "#908caa" })
hi(0, "PmenuExtra", { bg = "#1f1d2e", fg = "#6e6a86" })
hi(0, "PmenuExtraSel", { bg = "#26233a", fg = "#908caa" })
hi(0, "PmenuKind", { fg = "#9ccfd8" })
hi(0, "PmenuKindSel", { bg = "#26233a", fg = "#908caa" })
hi(0, "PmenuSbar", { bg = "#1f1d2e" })
hi(0, "PmenuSel", { bg = "#313244" })
hi(0, "PmenuThumb", { bg = "#6e6a86" })
hi(0, "PounceAccept", { bg = "#43293a", fg = "#eb6f92" })
hi(0, "PounceAcceptBest", { bg = "#453935", fg = "#f6c177" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#c4a7e7" })
hi(0, "PreProc", { link = "PreCondit" })
hi(0, "Question", { fg = "#f6c177" })
hi(0, "RainbowDelimiterBlue", { fg = "#31748f" })
hi(0, "RainbowDelimiterCyan", { fg = "#9ccfd8" })
hi(0, "RainbowDelimiterGreen", { fg = "#95b1ac" })
hi(0, "RainbowDelimiterOrange", { fg = "#ebbcba" })
hi(0, "RainbowDelimiterRed", { fg = "#eb6f92" })
hi(0, "RainbowDelimiterViolet", { fg = "#c4a7e7" })
hi(0, "RainbowDelimiterYellow", { fg = "#f6c177" })
hi(0, "RedrawDebugClear", { bg = "#f6c177", fg = "#191724" })
hi(0, "RedrawDebugComposed", { bg = "#31748f", fg = "#191724" })
hi(0, "RedrawDebugRecompose", { bg = "#eb6f92", fg = "#191724" })
hi(0, "ReferencesCount", { fg = "#ebbcba" })
hi(0, "ReferencesIcon", { fg = "#ebbcba" })
hi(0, "RenderMarkdownBullet", { fg = "#ebbcba" })
hi(0, "RenderMarkdownChecked", { fg = "#9ccfd8" })
hi(0, "RenderMarkdownCode", { bg = "#26233a" })
hi(0, "RenderMarkdownCodeInline", { bg = "#26233a", fg = "#f6c177" })
hi(0, "RenderMarkdownDash", { fg = "#6e6a86" })
hi(0, "RenderMarkdownH1Bg", { bg = "#3b344b" })
hi(0, "RenderMarkdownH2Bg", { bg = "#333c48" })
hi(0, "RenderMarkdownH3Bg", { bg = "#433842" })
hi(0, "RenderMarkdownH4Bg", { bg = "#453935" })
hi(0, "RenderMarkdownH5Bg", { bg = "#1e2a39" })
hi(0, "RenderMarkdownH6Bg", { bg = "#32363f" })
hi(0, "RenderMarkdownQuote", { fg = "#908caa" })
hi(0, "RenderMarkdownTableFill", { link = "Conceal" })
hi(0, "RenderMarkdownTableHead", { fg = "#908caa" })
hi(0, "RenderMarkdownTableRow", { fg = "#908caa" })
hi(0, "RenderMarkdownUnchecked", { fg = "#908caa" })
hi(0, "Repeat", { fg = "#31748f" })
hi(0, "SagaShadow", { bg = "#26233a" })
hi(0, "Search", { bg = "#453935", fg = "#e0def4" })
hi(0, "SignAdd", { fg = "#9ccfd8" })
hi(0, "SignChange", { fg = "#ebbcba" })
hi(0, "SignColumn", {})
hi(0, "SignDelete", { fg = "#eb6f92" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImage1", { fg = "#8c801f", sp = "#000001" })
hi(0, "SnacksImage2", { fg = "#8c8020", sp = "#000002" })
hi(0, "SnacksImage3", { fg = "#8c8021", sp = "#000003" })
hi(0, "SnacksIndent", { fg = "#26233a" })
hi(0, "SnacksIndentBlank", { fg = "#26233a" })
hi(0, "SnacksIndentChunk", { fg = "#26233a" })
hi(0, "SnacksIndentScope", { fg = "#908caa" })
hi(0, "SnacksPickerMatch", { bold = true, fg = "#ebbcba" })
hi(0, "Special", { fg = "#9ccfd8" })
hi(0, "SpecialComment", { fg = "#c4a7e7" })
hi(0, "SpecialKey", { fg = "#9ccfd8" })
hi(0, "SpellBad", { sp = "#908caa" })
hi(0, "SpellCap", { sp = "#908caa" })
hi(0, "SpellLocal", { sp = "#908caa" })
hi(0, "SpellRare", { sp = "#908caa" })
hi(0, "Statement", { bold = true, fg = "#31748f" })
hi(0, "StatusLine", { fg = "#908caa" })
hi(0, "StatusLineNC", { fg = "#6e6a86" })
hi(0, "StatusLineTerm", { bg = "#31748f", fg = "#191724" })
hi(0, "StatusLineTermNC", { bg = "#274f64", fg = "#191724" })
hi(0, "StorageClass", { fg = "#9ccfd8" })
hi(0, "String", { fg = "#32748f" })
hi(0, "Structure", { fg = "#9ccfd8" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { fg = "#908caa" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bold = true, fg = "#e0def4" })
hi(0, "Tag", { fg = "#9ccfd8" })
hi(0, "TargetWord", { fg = "#c4a7e7" })
hi(0, "TelescopeBorder", { fg = "#6e6a86" })
hi(0, "TelescopeMatching", { fg = "#ebbcba" })
hi(0, "TelescopeNormal", { fg = "#908caa" })
hi(0, "TelescopePromptNormal", { fg = "#e0def4" })
hi(0, "TelescopePromptPrefix", { fg = "#908caa" })
hi(0, "TelescopeSelection", { bold = true, fg = "#e0def4" })
hi(0, "TelescopeSelectionCaret", { fg = "#ebbcba" })
hi(0, "TelescopeTitle", { bold = true, fg = "#9ccfd8" })
hi(0, "Title", { bold = true, fg = "#9ccfd8" })
hi(0, "Todo", { bg = "#433842", fg = "#ebbcba" })
hi(0, "TreesitterContextLineNumber", { fg = "#ebbcba" })
hi(0, "TroubleCount", { bg = "#1f1d2e", fg = "#c4a7e7" })
hi(0, "TroubleText", { fg = "#908caa" })
hi(0, "Type", { fg = "#9ccfd8" })
hi(0, "Underlined", { fg = "#c4a7e7", underline = true })
hi(0, "VertSplit", { fg = "#6e6a86" })
hi(0, "VimwikiHR", { fg = "#908caa" })
hi(0, "VimwikiHeader1", { link = "markdownH1" })
hi(0, "VimwikiHeader2", { link = "markdownH2" })
hi(0, "VimwikiHeader3", { link = "markdownH3" })
hi(0, "VimwikiHeader4", { link = "markdownH4" })
hi(0, "VimwikiHeader5", { link = "markdownH5" })
hi(0, "VimwikiHeader6", { link = "markdownH6" })
hi(0, "VimwikiHeaderChar", { fg = "#908caa" })
hi(0, "VimwikiLink", { link = "markdownUrl" })
hi(0, "VimwikiList", { fg = "#c4a7e7" })
hi(0, "VimwikiNoExistsLink", { fg = "#eb6f92" })
hi(0, "Visual", { bg = "#332d41" })
hi(0, "WarningMsg", { bold = true, fg = "#f6c177" })
hi(0, "WhichKey", { fg = "#c4a7e7" })
hi(0, "WhichKeyBorder", { fg = "#6e6a86" })
hi(0, "WhichKeyDesc", { fg = "#f6c177" })
hi(0, "WhichKeyGroup", { fg = "#9ccfd8" })
hi(0, "WhichKeyIcon", { fg = "#31748f" })
hi(0, "WhichKeyIconAzure", { fg = "#31748f" })
hi(0, "WhichKeyIconBlue", { fg = "#31748f" })
hi(0, "WhichKeyIconCyan", { fg = "#9ccfd8" })
hi(0, "WhichKeyIconGreen", { fg = "#95b1ac" })
hi(0, "WhichKeyIconGrey", { fg = "#908caa" })
hi(0, "WhichKeyIconOrange", { fg = "#ebbcba" })
hi(0, "WhichKeyIconPurple", { fg = "#c4a7e7" })
hi(0, "WhichKeyIconRed", { fg = "#eb6f92" })
hi(0, "WhichKeyIconYellow", { fg = "#f6c177" })
hi(0, "WhichKeySeparator", { fg = "#908caa" })
hi(0, "WhichKeyTitle", { link = "FloatTitle" })
hi(0, "WhichKeyValue", { fg = "#ebbcba" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "WinBar", { bg = "#1f1d2e", fg = "#908caa" })
hi(0, "WinBarNC", { bg = "#1d1b2a", fg = "#6e6a86" })
hi(0, "WinSeparator", { fg = "#6e6a86" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "dircolorsColor0_31", { bold = true, fg = "#008b8b" })
hi(0, "dircolorsColor0_32", { bold = true, fg = "#008b8b" })
hi(0, "dircolorsColor10_31", { fg = "#008b8b" })
hi(0, "dircolorsColor10_32", { fg = "#008b8b" })
hi(0, "dircolorsColor11_31", { fg = "#808080", italic = true })
hi(0, "dircolorsColor11_32", { fg = "#808080", italic = true })
hi(0, "dircolorsColor12_31", { fg = "#808080" })
hi(0, "dircolorsColor12_32", { fg = "#808080" })
hi(0, "dircolorsColor1_31", { bold = true, fg = "#8b0000" })
hi(0, "dircolorsColor1_32", { bold = true, fg = "#8b0000" })
hi(0, "dircolorsColor2_31", { fg = "#00008b" })
hi(0, "dircolorsColor2_32", { fg = "#00008b" })
hi(0, "dircolorsColor3_31", { bold = true, fg = "#00008b" })
hi(0, "dircolorsColor3_32", { bold = true, fg = "#00008b" })
hi(0, "dircolorsColor4_31", { fg = "#bbbb00" })
hi(0, "dircolorsColor4_32", { fg = "#bbbb00" })
hi(0, "dircolorsColor5_31", { bold = true, fg = "#8b008b" })
hi(0, "dircolorsColor5_32", { bold = true, fg = "#8b008b" })
hi(0, "dircolorsColor6_31", { bold = true, fg = "#bbbb00" })
hi(0, "dircolorsColor6_32", { bold = true, fg = "#bbbb00" })
hi(0, "dircolorsColor7_31", { bold = true, fg = "#006400" })
hi(0, "dircolorsColor7_32", { bold = true, fg = "#006400" })
hi(0, "dircolorsColor8_31", { bold = true, fg = "#8b0000" })
hi(0, "dircolorsColor8_32", { bold = true, fg = "#8b0000" })
hi(0, "dircolorsColor9_31", { fg = "#8b008b", italic = true })
hi(0, "dircolorsColor9_32", { fg = "#8b008b", italic = true })
hi(0, "healthError", { fg = "#eb6f92" })
hi(0, "healthSuccess", { fg = "#9ccfd8" })
hi(0, "healthWarning", { fg = "#f6c177" })
hi(0, "htmlArg", { fg = "#c4a7e7" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlBoldUnderline", { bold = true, underline = true })
hi(
  0,
  "htmlBoldUnderlineItalic",
  { bold = true, italic = true, underline = true }
)
hi(0, "htmlEndTag", { fg = "#908caa" })
hi(0, "htmlH1", { link = "markdownH1" })
hi(0, "htmlH2", { link = "markdownH2" })
hi(0, "htmlH3", { link = "markdownH3" })
hi(0, "htmlH4", { link = "markdownH4" })
hi(0, "htmlH5", { link = "markdownH5" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { link = "markdownUrl" })
hi(0, "htmlStrike", { strikethrough = true })
hi(0, "htmlTag", { fg = "#908caa" })
hi(0, "htmlTagN", { fg = "#e0def4" })
hi(0, "htmlTagName", { fg = "#9ccfd8" })
hi(0, "htmlUnderline", { underline = true })
hi(0, "htmlUnderlineItalic", { italic = true, underline = true })
hi(0, "lCursor", { bg = "#e0def4" })
hi(0, "markdownDelimiter", { fg = "#908caa" })
hi(0, "markdownH1", { bold = true, fg = "#c4a7e7" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#9ccfd8" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#ebbcba" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#f6c177" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#31748f" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#95b1ac" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { fg = "#c4a7e7", sp = "#c4a7e7", underline = true })
hi(0, "mkdCode", { fg = "#9ccfd8", italic = true })
hi(0, "mkdCodeDelimiter", { fg = "#ebbcba" })
hi(0, "mkdCodeEnd", { fg = "#9ccfd8" })
hi(0, "mkdCodeStart", { fg = "#9ccfd8" })
hi(0, "mkdFootnotes", { fg = "#9ccfd8" })
hi(0, "mkdID", { fg = "#9ccfd8", underline = true })
hi(0, "mkdInlineURL", { link = "markdownUrl" })
hi(0, "mkdLink", { link = "markdownUrl" })
hi(0, "mkdLinkDef", { link = "markdownUrl" })
hi(0, "mkdListItemLine", { fg = "#e0def4" })
hi(0, "mkdRule", { fg = "#908caa" })
hi(0, "mkdURL", { link = "markdownUrl" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#26233a"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#31748f"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ebbcba"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#31748f"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ebbcba"
g.terminal_color_15 = "#e0def4"
