-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "techbase"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@comment.danger", { bg = "#f71735", fg = "#ccd5e5" })
hi(0, "@comment.danger.comment", { bg = "#f71735", fg = "#ccd5e5" })
hi(0, "@comment.error", { bg = "#f71735", fg = "#ccd5e5" })
hi(0, "@comment.error.comment", { bg = "#f71735", fg = "#ccd5e5" })
hi(0, "@comment.note", { bg = "#ccd5e5", fg = "#191d23" })
hi(0, "@comment.note.comment", { bg = "#ccd5e5", fg = "#191d23" })
hi(0, "@comment.todo", { bg = "#a9b9ef", fg = "#191d23" })
hi(0, "@comment.todo.comment", { bg = "#a9b9ef", fg = "#191d23" })
hi(0, "@comment.warning", { bg = "#ffa630", fg = "#191d23" })
hi(0, "@comment.warning.comment", { bg = "#ffa630", fg = "#191d23" })
hi(0, "@conceal.markdown_inline", { link = "Operator" })
hi(0, "@constant.builtin", { link = "Constant" })
hi(0, "@function.call", { fg = "#ccd5e5" })
hi(0, "@function.method.call", { fg = "#ccd5e5" })
hi(0, "@lsp.mod.deprecated", {})
hi(0, "@lsp.type.class", {})
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", {})
hi(0, "@lsp.type.enum", {})
hi(0, "@lsp.type.enumMember", {})
hi(0, "@lsp.type.event", {})
hi(0, "@lsp.type.function", {})
hi(0, "@lsp.type.interface", {})
hi(0, "@lsp.type.keyword", {})
hi(0, "@lsp.type.macro", {})
hi(0, "@lsp.type.method", {})
hi(0, "@lsp.type.modifier", {})
hi(0, "@lsp.type.namespace", {})
hi(0, "@lsp.type.number", {})
hi(0, "@lsp.type.operator", {})
hi(0, "@lsp.type.parameter", {})
hi(0, "@lsp.type.property", {})
hi(0, "@lsp.type.regexp", {})
hi(0, "@lsp.type.string", {})
hi(0, "@lsp.type.struct", {})
hi(0, "@lsp.type.type", {})
hi(0, "@lsp.type.typeParameter", {})
hi(0, "@lsp.type.variable", {})
hi(0, "@markup.environment.latex", { link = "markdownCodeBlock" })
hi(0, "@markup.heading", { link = "Function" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#191d23", fg = "#191d23", nocombine = true, sp = "#ccd5e5", underdouble = true })
hi(0, "@markup.heading.1.latex", { link = "String" })
hi(0, "@markup.heading.1.markdown", { fg = "#6a8be3" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#191d23", fg = "#191d23", nocombine = true, sp = "#ccd5e5", underline = true })
hi(0, "@markup.heading.2.latex", { link = "String" })
hi(0, "@markup.heading.2.markdown", { fg = "#6a8be3" })
hi(0, "@markup.heading.3.latex", { link = "String" })
hi(0, "@markup.heading.3.markdown", { fg = "#6a8be3" })
hi(0, "@markup.heading.4.latex", { link = "String" })
hi(0, "@markup.heading.4.markdown", { fg = "#6a8be3" })
hi(0, "@markup.heading.5.markdown", { fg = "#6a8be3" })
hi(0, "@markup.heading.6.markdown", { fg = "#6a8be3" })
hi(0, "@markup.link.label", { link = "String" })
hi(0, "@markup.link.latex", { link = "Keyword" })
hi(0, "@markup.link.markdown_inline", { fg = "#ccd5e5" })
hi(0, "@markup.list.checked.markdown", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked.markdown", { link = "DiagnosticError" })
hi(0, "@markup.quote.markdown", { link = "markdownBlockquote" })
hi(0, "@markup.raw.block", { link = "markdownCodeBlock" })
hi(0, "@markup.raw.markdown_inline", { bg = "#20252e", fg = "#a9b9ef" })
hi(0, "@method.call", { fg = "#ccd5e5" })
hi(0, "@module", { fg = "#ccd5e5" })
hi(0, "@module.latex", { link = "Function" })
hi(0, "@namespace", { fg = "#6a8be3" })
hi(0, "@number.comment", { link = "Comment" })
hi(0, "@property", { fg = "#ccd5e5" })
hi(0, "@punctuation", { fg = "#ccd5e5" })
hi(0, "@punctuation.special.latex", { link = "Function" })
hi(0, "@punctuation.special.markdown", { link = "@markup.quote.markdown" })
hi(0, "@string.documentation", { link = "Comment" })
hi(0, "@string.escape", { link = "@string.regex" })
hi(0, "@string.regex", { fg = "#0ec256" })
hi(0, "@string.special.symbol", { link = "@string.regex" })
hi(0, "@text.literal", { fg = "#ccd5e5" })
hi(0, "@text.reference", { link = "String" })
hi(0, "@text.uri", { fg = "#a9b9ef", underline = true })
hi(0, "@type.builtin", { link = "@type" })
hi(0, "Added", { bg = "#1e3a34", fg = "#9fdacc" })
hi(0, "AerialLine", { bg = "#1f242d" })
hi(0, "BlinkCmpDoc", { link = "Pmenu" })
hi(0, "BlinkCmpDocBorder", { bg = "#1c2127", fg = "#2a2f39" })
hi(0, "BlinkCmpDocSeparator", { fg = "#2a2f39" })
hi(0, "BlinkCmpGhostText", { link = "NonText" })
hi(0, "BlinkCmpKind", { fg = "#6a8be3" })
hi(0, "BlinkCmpLabel", { fg = "#d6ddea" })
hi(0, "BlinkCmpLabelDescription", { fg = "#363848" })
hi(0, "BlinkCmpLabelDetail", { link = "NonText" })
hi(0, "BlinkCmpLabelMatch", { link = "PmenuMatch" })
hi(0, "BlinkCmpMenuBorder", { bg = "#1c2127", fg = "#2a2f39" })
hi(0, "BlinkCmpMenuSelection", { link = "PmenuMatchSel" })
hi(0, "Changed", { bg = "#1f2b5c", fg = "#b7c4ff" })
hi(0, "Character", { link = "String" })
hi(0, "CmpItemAbbrDeprecated", { strikethrough = true })
hi(0, "CmpItemAbbrMatch", { link = "PmenuMatch" })
hi(0, "CmpItemKind", { link = "Keyword" })
hi(0, "ColorColumn", { bg = "#242932" })
hi(0, "Comment", { fg = "#474b65" })
hi(0, "Conceal", { fg = "#ccd5e5" })
hi(0, "Constant", { fg = "#bcb6ec" })
hi(0, "CurSearch", { bg = "#b85b53", fg = "#191d23" })
hi(0, "Cursor", { bg = "#5dcd9a" })
hi(0, "CursorLine", { bg = "#242932" })
hi(0, "CursorLineNr", { fg = "#ccd5e5" })
hi(0, "Delimiter", { fg = "#ccd5e5" })
hi(0, "DiagnosticError", { fg = "#f71735" })
hi(0, "DiagnosticHint", { fg = "#d6ddea" })
hi(0, "DiagnosticInfo", { fg = "#1a8c9b" })
hi(0, "DiagnosticOk", { fg = "#0ec256" })
hi(0, "DiagnosticSignError", { fg = "#f71735" })
hi(0, "DiagnosticSignHint", { fg = "#d6ddea" })
hi(0, "DiagnosticSignInfo", { fg = "#1a8c9b" })
hi(0, "DiagnosticSignOk", { fg = "#0ec256" })
hi(0, "DiagnosticSignWarn", { fg = "#ffa630" })
hi(0, "DiagnosticUnderlineError", { sp = "#d2142d", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#b6bcc7", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#167784", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#0ca549", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d98d29", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#474b65", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#f71735" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#d6ddea" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#1a8c9b" })
hi(0, "DiagnosticVirtualTextOk", { fg = "#0ec256" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#ffa630" })
hi(0, "DiagnosticWarn", { fg = "#ffa630" })
hi(0, "DiffAdd", { link = "Added" })
hi(0, "DiffChange", { link = "Changed" })
hi(0, "DiffDelete", { link = "Removed" })
hi(0, "DiffText", { bg = "#6a8be3" })
hi(0, "Directory", { fg = "#6a8be3" })
hi(0, "EdgyIcon", { bg = "#1b1f25", fg = "#474b65" })
hi(0, "EdgyIconActive", { link = "EdgyIcon" })
hi(0, "EdgyNormal", { bg = "#1b1f25", fg = "#474b65" })
hi(0, "EdgyTitle", { bg = "#1b1f25" })
hi(0, "EdgyWinBar", { bg = "#1b1f25", sp = "#20252e", underline = true })
hi(0, "Error", { fg = "#f71735" })
hi(0, "ErrorMsg", { link = "Error" })
hi(0, "FloatBorder", { bg = "#1c2127", fg = "#2a2f39" })
hi(0, "FloatTitle", { bg = "#1c2127", fg = "#6a8be3" })
hi(0, "FoldColumn", { link = "NonText" })
hi(0, "Folded", { bg = "#242932", fg = "#a9b9ef" })
hi(0, "Function", { fg = "#6a8be3" })
hi(0, "GitSignsAdd", { fg = "#366a4c" })
hi(0, "GitSignsAddInline", { link = "Added" })
hi(0, "GitSignsAddLnInline", { bg = "#35665b", fg = "#ccd5e5" })
hi(0, "GitSignsChange", { fg = "#3f58bb" })
hi(0, "GitSignsChangeInline", { link = "DiffText" })
hi(0, "GitSignsChangeLnInline", { link = "Changed" })
hi(0, "GitSignsChangedelete", { link = "GitSignsChange" })
hi(0, "GitSignsCurrentLineBlame", { link = "NonText" })
hi(0, "GitSignsDelete", { fg = "#942b27" })
hi(0, "GitSignsDeleteInline", { link = "Removed" })
hi(0, "GitSignsDeleteLnInline", { bg = "#662e3a", fg = "#ccd5e5" })
hi(0, "GitSignsDeleteVirtLn", { link = "Removed" })
hi(0, "GitSignsDeleteVirtLnInLine", { link = "Removed" })
hi(0, "GitSignsStagedAdd", { fg = "#1b3526" })
hi(0, "GitSignsStagedAddCul", { fg = "#1b3526" })
hi(0, "GitSignsStagedAddLn", { bg = "#1e3a34", fg = "#4f6d66" })
hi(0, "GitSignsStagedAddNr", { fg = "#1b3526" })
hi(0, "GitSignsStagedChange", { fg = "#202c5e" })
hi(0, "GitSignsStagedChangeCul", { fg = "#1f2c5d" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1f2b5c", fg = "#5b627f" })
hi(0, "GitSignsStagedChangeNr", { fg = "#1f2c5d" })
hi(0, "GitSignsStagedChangedelete", { link = "GitSignsStagedChange" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#1f2c5d" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1f2b5c", fg = "#5b627f" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#1f2c5d" })
hi(0, "GitSignsStagedDelete", { fg = "#4a1614" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#4a1513" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#4a1513" })
hi(0, "GitSignsStagedTopdelete", { link = "GitSignsStagedDelete" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#4a1513" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#4a1513" })
hi(0, "GitSignsStagedUntracked", { link = "GitSignsStagedAdd" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#1b3526" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#1e3a34", fg = "#4f6d66" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#1b3526" })
hi(0, "GitSignsTopdelete", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { link = "NonText" })
hi(0, "GitSignsVirtLnum", { link = "LineNr" })
hi(0, "Headline1Bg", { bg = "#323449", fg = "#f265b5" })
hi(0, "Headline1Fg", { bold = true, fg = "#f265b5" })
hi(0, "Headline2Bg", { bg = "#323449", fg = "#37f499" })
hi(0, "Headline2Fg", { bold = true, fg = "#37f499" })
hi(0, "Headline3Bg", { bg = "#323449", fg = "#04d1f9" })
hi(0, "Headline3Fg", { bold = true, fg = "#04d1f9" })
hi(0, "Headline4Bg", { bg = "#323449", fg = "#a48cf2" })
hi(0, "Headline4Fg", { bold = true, fg = "#a48cf2" })
hi(0, "Headline5Bg", { bg = "#323449", fg = "#f1fc79" })
hi(0, "Headline5Fg", { bold = true, fg = "#f1fc79" })
hi(0, "Headline6Bg", { bg = "#323449", fg = "#f7c67f" })
hi(0, "Headline6Fg", { bold = true, fg = "#f7c67f" })
hi(0, "Identifier", { fg = "#ccd5e5" })
hi(0, "IlluminatedWordRead", { link = "IlluminatedWordText" })
hi(0, "IlluminatedWordText", { link = "MatchParen" })
hi(0, "IlluminatedWordWrite", { link = "IlluminatedWordText" })
hi(0, "IncSearch", { link = "Search" })
hi(0, "Keyword", { fg = "#a9b9ef" })
hi(0, "Label", { link = "Conditional" })
hi(0, "LazyButton", { bg = "#1f242d" })
hi(0, "LazyButtonActive", { link = "Search" })
hi(0, "LazyCommitIssue", { link = "Number" })
hi(0, "LazyCommitType", { link = "@markup.heading.gitcommit" })
hi(0, "LazyH2", { link = "FloatTitle" })
hi(0, "LazyProgressDone", { link = "LazyComment" })
hi(0, "LazyProgressTodo", { link = "FloatBorder" })
hi(0, "LazyReasonCmd", { link = "Comment" })
hi(0, "LazyReasonColorscheme", { link = "Comment" })
hi(0, "LazyReasonEvent", { link = "Comment" })
hi(0, "LazyReasonFt", { link = "Comment" })
hi(0, "LazyReasonPlugin", { link = "Comment" })
hi(0, "LazyReasonRequire", { link = "Comment" })
hi(0, "LazyReasonSource", { link = "Comment" })
hi(0, "LazyReasonStart", { link = "Comment" })
hi(0, "LazySpecial", { link = "Comment" })
hi(0, "LineNr", { link = "NonText" })
hi(0, "LspCodeLens", { fg = "#363848" })
hi(0, "LspSignatureActiveParameter", { sp = "#ccd5e5", underline = true })
hi(0, "MasonBackdrop", { link = "NormalFloat" })
hi(0, "MasonError", { link = "DiagnosticError" })
hi(0, "MasonHeader", { link = "FloatTitle" })
hi(0, "MasonHeaderSecondary", { link = "Search" })
hi(0, "MasonHeading", { link = "FloatTitle" })
hi(0, "MasonHighlight", { fg = "#474b65" })
hi(0, "MasonHighlightBlock", { bg = "#20252e" })
hi(0, "MasonHighlightBlockBold", { link = "Search" })
hi(0, "MasonHighlightSecondary", { link = "Search" })
hi(0, "MasonLink", { fg = "#a9b9ef" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#20252e" })
hi(0, "MasonMutedBlockBold", { link = "Comment" })
hi(0, "MasonNormal", { link = "NormalFloat" })
hi(0, "MasonWarning", { link = "DiagnosticWarn" })
hi(0, "MatchArea", { link = "MatchParen" })
hi(0, "MatchParen", { bg = "#20252e", fg = "#e9b872" })
hi(0, "MiniCursorword", { link = "IlluminatedWordText" })
hi(0, "MiniHipatternsFixme", { bold = true, fg = "#f71735", reverse = true })
hi(0, "MiniHipatternsHack", { bold = true, fg = "#ffa630", reverse = true })
hi(0, "MiniHipatternsNote", { bold = true, fg = "#d6ddea", reverse = true })
hi(0, "MiniHipatternsTodo", { bold = true, fg = "#1a8c9b", reverse = true })
hi(0, "ModeMsg", { fg = "#bcb6ec" })
hi(0, "MoreMsg", { link = "ModeMsg" })
hi(0, "MsgArea", { fg = "#ccd5e5" })
hi(0, "MsgSeparator", { fg = "#1c2127" })
hi(0, "NoiceFormatProgressDone", { bg = "#e9b872", fg = "#191d23" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#363848" })
hi(0, "Normal", { bg = "#191d23", fg = "#ccd5e5" })
hi(0, "NormalFloat", { bg = "#1c2127", fg = "#d6ddea" })
hi(0, "Number", { fg = "#b85b53" })
hi(0, "Operator", { fg = "#b09884" })
hi(0, "Pmenu", { bg = "#1c2127", fg = "#d6ddea" })
hi(0, "PmenuMatch", { fg = "#6a8be3" })
hi(0, "PmenuMatchSel", { link = "PmenuSel" })
hi(0, "PmenuSel", { bg = "#1f242d" })
hi(0, "PmenuThumb", { bg = "#363848" })
hi(0, "PreProc", { fg = "#ccd5e5" })
hi(0, "Question", { fg = "#74baa8" })
hi(0, "QuickFixLine", { link = "Search" })
hi(0, "Removed", { bg = "#3a1a21", fg = "#ffc0c5" })
hi(0, "RenderMarkdownCodeInline", { bg = "#323449", fg = "#f7c67f" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "Search", { bg = "#e9b872", fg = "#191d23" })
hi(0, "SignColumn", { fg = "#ccd5e5" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#ccd5e5" })
hi(0, "Special", { fg = "#ccd5e5" })
hi(0, "SpecialComment", { fg = "#e9b872" })
hi(0, "SpecialKey", { fg = "#e9b872" })
hi(0, "Statement", { link = "Keyword" })
hi(0, "StatusLine", { fg = "#ccd5e5" })
hi(0, "StatusLineNC", {})
hi(0, "String", { fg = "#74baa8" })
hi(0, "Substitute", { bg = "#20252e", fg = "#74baa8" })
hi(0, "TabLine", { bg = "#191d23", fg = "#474b65" })
hi(0, "TabLineFill", { bg = "#191d23", fg = "#363848" })
hi(0, "TabLineSel", { fg = "#6a8be3" })
hi(0, "Tag", { fg = "#ccd5e5" })
hi(0, "TermCursor", { link = "Cursor" })
hi(0, "Title", { link = "Directory" })
hi(0, "Todo", { link = "SpecialComment" })
hi(0, "Type", { fg = "#a9b9ef" })
hi(0, "Visual", { bg = "#121e42" })
hi(0, "VisualNonText", { bg = "#121e42", fg = "#4833a4" })
hi(0, "WarningMsg", { link = "Error" })
hi(0, "WinBar", { fg = "#d6ddea" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#20252e" })
hi(0, "diffAdded", { link = "Added" })
hi(0, "diffChanged", { link = "Changed" })
hi(0, "diffRemoved", { link = "Removed" })
hi(0, "dosiniHeader", { link = "@markup.heading.1.markdown" })
hi(0, "dosiniLabel", { link = "@property" })
hi(0, "gitcommitArrow", { link = "Statement" })
hi(0, "gitcommitBlank", { link = "Added" })
hi(0, "gitcommitBranch", { link = "Added" })
hi(0, "gitcommitDiscarded", { link = "Added" })
hi(0, "gitcommitDiscardedFile", { link = "Added" })
hi(0, "gitcommitDiscardedType", { link = "Removed" })
hi(0, "gitcommitSummary", { link = "Directory" })
hi(0, "gitcommitType", { fg = "#bcb6ec" })
hi(0, "gitcommitUnmerged", { link = "Added" })
hi(0, "helpCommand", { fg = "#ccd5e5" })
hi(0, "helpExample", { link = "String" })
hi(0, "helpHyperTextEntry", { link = "Directory" })
hi(0, "helpOption", { fg = "#ccd5e5" })
hi(0, "helpVim", { fg = "#ccd5e5" })
hi(0, "lCursor", { bg = "#ccd5e5", fg = "#191d23" })
hi(0, "markdownBlockquote", { fg = "#7e8193" })
hi(0, "markdownCodeBlock", { bg = "#20252e" })
hi(0, "markdownHeadingRule", { link = "markdownRule" })
hi(0, "markdownLinkText", { link = "String" })
hi(0, "markdownListMarker", { fg = "#ccd5e5" })
hi(0, "markdownRule", { link = "NonText" })
hi(0, "markdownUrl", { link = "@text.uri" })

-- No terminal colors defined
