local M = {}
M.kind_icons = {
	File = "",
	Module = "",
	Namespace = "",
	Package = "",
	Class = "",
	Method = "m",
	Property = "",
	Field = "",
	Constructor = "",
	Enum = "",
	Interface = "",
	Function = "󰊕",
	Variable = "",
	Constant = "",
	String = "",
	Number = "",
	Boolean = "",
	Array = "",
	Object = "",
	Key = "󰌋",
	Null = "",
	EnumMember = "",
	Struct = "",
	Event = "",
	Operator = "",
	TypeParameter = "",
}

return M
