# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/629db788-e07d-4df1-b07c-34b5f0111f5d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2E84-1780";
    fsType = "vfat";
  };

  fileSystems."/mnt/mint" = {
    device = "/dev/disk/by-uuid/e695417a-7b4b-4d45-a723-eef6bf28b4c8";
    fsType = "ext4";
  };

  fileSystems."/mnt/acer" = {
    device = "/dev/disk/by-uuid/F2B04A21B049ED23";
    fsType = "ntfs";
  };

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-uuid/01D989993966A490";
    fsType = "ntfs";
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/263E6A633E6A2BCD";
    fsType = "ntfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/01c1b93e-ea7a-455a-ab03-b9a34996b587";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
