return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "prettierd",
      "eslint_d",
      "rust-analyzer",
      "typescript-language-server",
      "tailwindcss-language-server",
      "gopls",
      "emmet-ls",
      "css-lsp",
      "dockerfile-language-server",
      "docker-compose-language-service",
      "clangd",
      "ansible-language-server",
      "mypy",
      "ruff",
      "pyright",
      "black",
    },
  },
}
