return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    auto_install = true,
    ensure_installed = {
      "c",
      "cpp",
      "javascript",
      "html",
      "css",
      "rust",
      "lua",
      "bash",
      "typescript",
      "tsx",
      "python",
      "go",
      "yaml",
      "markdown",
      "markdown_inline",
      "ninja",
      "rst",
      "toml",
    },
  },
}
