# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelModules = [
    "kvm-intel"
    "nvidia"
  ];

  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "button.lid_init_state=open"
    "snd_hda_intel.power_save=0"
  ];

  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024;
    }
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/39b77597-335c-48cb-ab31-2b83b56dc075";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0F5E-64D2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/263E6A633E6A2BCD";
    fsType = "ntfs";
  };

  fileSystems."/mnt/game" = {
    device = "/dev/disk/by-uuid/5C3E79013E78D58C";
    fsType = "ntfs";
  };

  fileSystems."/export/media" = {
    device = "/mnt/media";
    options = [ "bind" ];
  };

  services.nfs.server = {
    exports = ''
      /export     192.168.1.0/24(rw,fsid=0,no_subtree_check)
      /export/media  192.168.1.0/24(rw,async,nohide,insecure,no_subtree_check)
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
